### ISSUE TITLE
The ultimate Steam Release checklist

### ISSUE THREAD

**Issue by MaxIsJoe** [unitystation/unitystation#10011]
We've discussed on discord a general plan on what we'll be doing to push a steam release. However, there wasn't any officially documented track lists for our plans and required bug fixes, until now.
This issue is meant to officially track all related submitted issues and tasks that are required to be done for unitystation's steam release.

We will not impose a deadline on ourselves, nor will we promise a speculative date on when all these tasks are finished.
However, we have an unofficial gentlemen's agreement to not do any more major reworks or touch core systems unless it is to fix a big design flaw, fix performance issues and/or the intention is to improve the user experience (UX), or stabilize an already broken or outdated system. 

We'd like to avoid any and all feature freezes as it slows down the game's development significantly. As a result, our main focus at the moment is polish, finishing gameplay loops and stability. We heavily discourage any major changes outside what is outlined in this checklist.

Once 90% of all these issues are done, we can safely consider UnityStation ready for a steam release.

_Note: This list will be updated as time goes by when more issues popup, and we receive more feedback from players._

## Security

Mandatory for Steam Release.

- [x] Sandboxing (https://github.com/unitystation/stationhub/pull/212)
- [X] Safe Url Open #9987
- [x] Removing Firebase and installing our own django service/solution ( #9824 )
- [x] #10012
- [x] Update mirror to latest version.
- [ ] #11271
- [x] Patch unsecue unity functions like: `UnityEngine.Events.UnityEvent`, `GetValidMethodInfo`

## Bugs

- [ ] #9966
- [x] #9964
- [x] #9962
- [x] #9835
- [x] #9751
- [ ] #9712
- [x] #9690
- [x] #9593
- [x] #9458
- [x] #2423
- [ ] #9548
- [x] #9515
- [x] #9499
- [x] #9498
- [x] #9467
- [x] #4914
- [x] #4676
- [x] #5512
- [ ] #8137
- [x] #10043
- [x] #10079 
- [x] Find what's interfering with the `Laydown` component that causes players to always appear standing up when they should be laying down or being set sideways.
- [x] Airlocks will randomly flash their red lights after a player with no access interacts with it, and will stay stuck in that state until someone opens the door.
- [x] Fix players failing to do any interactions inside moving shuttles.
- [x] Server has a 50/50 chance to crash whenever `free-power` admin command is used.
- [ ] Players have issues logging in for the first time when attempting to create characters.
- [x] Ash Walkers break way too often. 
- [x] if you buckle yourself into an office chair, lay down, and then start rapidly grappling yourself and throwing/moving around, it puts massive strain on the server and can reliably crash it. ( wasn't able to replicate it )
- [x] Attempting to teleport as an admin to other players may result in the admin getting teleported to their last ghost's location instead of where the player actually is.
- [x] Fix multiple mobs pushing each other through walls when they're crammed in a small room.
- [x] Airlocks get their "access denied" animation stuck after multiple uses.

## Features / UX

- [ ] #10500
- [ ] Finalize Trauma ( #6272 )
- - [ ] Add trauma treatments.
- - [ ] Add proper trauma stages/logic for blunt force trauma
- - [ ] Add the ability to incapacitate limbs and render them unusable when reaching 3rd stage of blunt trauma
- - [ ] Add infections and their treatments.
- - [x] Add sound feedback for effects of trauma.
- - [ ] Update the UV pen light to be used for preventing infection or treating light infections.
- [x] Resume and finish work on sicknesses.
- - [x] Random Cures for rarer and more dangerous sicknesses + Cure Clues system
- - [ ] Sickness immunity based on species, age, etc.
- [ ] Xenobiology requires more content for players to engage with.
- - [ ] Unique sprites are required for its content (and maybe just some sprite passes on stuff like potions)
- - [ ] Move xenobio mobs to MobV2
- [ ] Genetics requires a lot more polish.
- - [ ] Rebalancing is required.
- - [ ] Geneticist related UI requires an overhaul both in the visual and UX side. 
- [x] In-game mapping
- - [x] JSON map loading/saving
- - [x] Improve current in-game mapping tool to be as powerful if not better than the editor's current mapping tools. 
- - [ ] Add a game-mode for players and developers to enter a mapping mode where they can edit and create entire maps and blueprints to be shared.
- [x] Improve the UX of piloting shuttles.
- - [x] Piloting a shuttle should be done inside a large radar window that uses a normal minimap with RenderTextures for accuracy and stability.
- optional: Allow for rotational movement.
- [ ] Lawyers need more tools to be a legal professional  ~~pain in the ass~~ on the station. 
- - Lawyers need documents in their office with all crewmate's [contracts](https://github.com/Skyrat-SS13/Skyrat-tg/blob/f053e952f270f8a71fcefbc18dbda1c6f5188303/code/modules/paperwork/contract.dm#L3) in a cabinet.
- - Court rooms need to be properly mapped near security departments.
- - Stamps, signing, clipboards and files need to be added. This is generally a good thing for all departments but lawyers and cargo need it most now.
- - Gavel!
- [x] #4885
- [x] Visor Huds and Interactions
- - Security should be able to see and set the wanted status of other crewmates.
- - Medical should be able to see the current HP of a crewmate + their bleeding stacks 
- [x] #9933
- [x] Finish polishing Cyborgs and fix all related issues with them.
- - [ ] Work on medical cyborg functionality to be more useful and polished.
- [ ] Add the librarian job and finish all remaining jobs.
- [ ] Detectives need their universal recorder for interviews.
- [X] Add the option for a dropdown menu as an alternative to the radial menu.
- [ ]  #7878
- [x] #9988
- [x] #6416
- [ ] #9264
- [x] #9865
- [x] #9088
- [x] #8640
- [ ] Add `IHoverTooltip` info on more items and objects to allow new players to learn how to interact with objects more quickly.
- [x] Add Machine construction instructions to `IHoverTooltip`
- [ ] All UI should be windows. Do NOT shove anything at the top right tab thingy.
- [ ] #6990
- [x] Remove public terminals.
- [ ] Tutorial Station
- [ ] Expanding space/lavaland exploration content
- - [ ] #8919
- - [ ] Give ash walkers more content and reason to exist.
- - [ ] Add randomly generated structures in space for players to explore and obtain resources from.
- [x] Reactor balancing so newbies don't blow up the station instantly. ( change the default state just sits there and produces a lot of radiation making engineering radioactive and dangerous, to get an explosion traitor has to buy high yield uranium that they put into the reactor that causes the explosion when it melts down , still needs a bit of balancing to put some safeties on it )

- [x] UI and Fonts need some QT and QA, as a lot of elements keep overlapping each other and text is often harder to read according to players who played on SS14 and SS13.
- [x] Adding Plasma to containers and container pressure mechanics. 
- [ ] Move important mobs to MobsV2
- - [x] Mediborg, Floorbot and Beepsky.
- - [ ] All department pets
- - [ ] Lavaland mobs
- - [ ] Anicent Engineer mobs
- - [ ] Xenomorphs
- [x] Make sure that ID interactions work in more scenarios where the ID is placed inside a PDA.
- [x] Items are missing price labels, we should add/rebalance them.
- [x] Replace our current TTS solution with a local solution that uses Whisper or a smiliar library.
- [ ] A lot of maps are missing the more recent features and changes that we've added. We need to do pass on them to ensure that all stations are equpied with all the tools the crew will need.
- [ ] #10803 
- [ ] #11245 

## Admin Tools

The majority of these issues require us to solve #7179 first.

- [ ] Invisible mode for admins
- [x] Admin ranks
- [x] Admin Permissions
- [ ] Finer control over server components. (Such as gamemodes, chat filters, subsystems, etc)
- [ ] RCON Support
- [x] Expanded Admin Logging
- - [x] Logs for specific antagonist actions
- - [x] Logs for different player interactions with critical station systems, such atmospherics and electrical.
- - [ ] Logs for players joining, respawning and ghost roles.
- - [x] Logs for players getting spaced out of mainstation.
- - [x] Logs for players being put in harmful devices such as the incinerator

### Things to consider:

These aren't mandatory for the steam release, but they are preferable.

- Add shipwreck/shiptest gamemode. A singleplayer/co-op game mode designed for 1-8 players that involves players traveling across the stars to upgrade their small humble ship, conquer randomly generated dungeons, and re-establish connection with NT once more.
- Finish adding relays and the rest of the communications officer gameplay.
- Finish chemistry related bounties and add more reagent reactions.
- - If possible, simplify the creation of reagents and their reactions.
- Add the ability to auto-ghost upon death.
- #6787 
- #8930
- #8744
- #8641
- #8400
- #8165
- #7903
- #9667
- #6155
- #7556
- #9692
- #9691
- Progression system for loadouts and skillcaps.
- Some elements in movement needs to be re-adjusted and re-balanced.
- Allow consoles to be hacked to bypass ID requirements and expose special interactions for hacked consoles.
- Add admin interactions to ghost mode by updating the interactions system.
- Make admin ghosts their own separate entity to support things such as admin inventories and such.

### Criteria for expanding this list:

![7yirny](https://github.com/unitystation/unitystation/assets/34368774/96b3b7a7-3149-4fe5-96e0-dd3dd77decff)

The following criteria should help us easily know what is high priority and what isn't:

- Issue must be focused on improving the user experience for new players first
- Issue must provide additional value with minimal time spent on it (unless it's a bug or core gameplay content)
- Issue must be something that players have constantly requested in the past 4 years or from recent feedback.
- Issue must address critical missing features, jank or game breaking bugs.
- Issue must address an unfinished or poorly designed feature that is in dire need to be worked on.
- Any requests for new changes or features must be something a new player can easily detect without explanation.
- Any cosmetic changes should be purely for improving UX, and not to add it just for the sake of having it.
- Any one-liner requests are automatically denied and dismissed. Explain what you want and stop assuming that everyone understands what you're talking about (the hell is an RCON?)
- It is preferable to link to already submitted issues in our issue tracker. If there are no already opened issues for what you want to be added to this list, discuss it on discord first instead of needlessly filling up the comment section of this tracker.

_Your issue/request must meet three of the above crieteria to be added to the features list, while bugs only require one._

**Comment by Pockets-byte** [comment]
admin logging, RCON improvements. better direct game world interactions(IE an adminghost that acts like a player but is a ghost that can complete actions without a distance limit or timer) more alerting and awareness tools. at minimum for steam to be viable with an increased scale admin team

**Comment by Bod9001** [comment]
main TODOs for me?
map saving/loading and editing / 
move authentication /
admin tools general (rcon, For easy moderation logn stuff) 
shuttle rework /
character creator redo / ? (still a bug or two buggy) 
Spanish/portugese  player base??
homestation?? (depends on map saving)/player hook
TTS/STT /
extra antagonists

tutorial (very basic, and final message saying  ask other players on how to do stuff)  , 
admins tools (

quick command to teleport to places? teleporting to arbitrary chords ( Implement in device mover )/
ghost inventory,  /
#10890 alt/shift interaction modifies to spawn into player's inventory/inventory instead number prompt spawn multiple items /
connect Ahelp together in one long conversation, /
admin player notes  /
naughty list (watchlist),  (admin chat notice with a note when watchlisted player connects (#10880) /
#10882 bubble up some important logs to the chat ( with clicky icons? ) /
 jail button (admin cube  + restore location),  /
combat logs, /
#10883 Server Polls /
off-line indicator, /
server password  /
#10893 performance statistics /
logs page index don't update?
some logs are blank?
L and r on admin logs /
save to string not implemented forgot to do /
Last touched log,  /
#10884 AI law change viewer and history /
mind/possession manager /
in game map saver, /
)

#10881 download log
#10886 Faiths control max
#10891 signal Lister
#10888 manifest modifying?
#10885 Better Smiting more of a fun meh not too important
 #10892 some way to specify the contents of a supply pod, maybe in a separate staging area
#10887 matrix management? idk jumping to and all that stuff
#10879 changing in game? Admins and Hosts 
holy Grail replay?, 
 )
admin  Logs /
login fixes + hub update
bug fixes and polishing

**Comment by Bod9001** [comment]
security checking on the docker builds

**Comment by Bod9001** [comment]
getting killed = instant ghost?  /

**Comment by MaxIsJoe** [comment]
> getting killed = instant ghost?

idk if this is a feature request or a bug

**Comment by Bod9001** [comment]
feature request, since players want to see their destruction of a suicide bomb

**Comment by Bod9001** [comment]
steam account integration  (not done), with Django (done), no login required

**Comment by Bod9001** [comment]
cleanup misinformation, start doing is about a month before

**Comment by Bod9001** [comment]
Locker highlight fix

**Comment by MaxIsJoe** [comment]
> Locker highlight fix

It broke again?

**Comment by Bod9001** [comment]
Pro tip text not fitting

**Comment by Bod9001** [comment]
Pro tip , delay and stuff needs a review

**Comment by Bod9001** [comment]
animations for air  locks getting stuck , when spammed

**Comment by MaxIsJoe** [comment]
> animations for air locks getting stuck , when spammed

Is this important to fix? Because I don't think it is

**Comment by Bod9001** [comment]
well it's part of the polish for steam release

**Comment by MaxIsJoe** [comment]
ok

**Comment by Bod9001** [comment]
adding plasma to containers , empty canister vs full canister overpressure

**Comment by Bod9001** [comment]
option for old hud?

**Comment by MaxIsJoe** [comment]
> option for old hud?

not really necessary

**Comment by MaxIsJoe** [comment]
Bod, stop editing this without telling me.

**Comment by Bod9001** [comment]
medical cyborgs polish

**Comment by Bod9001** [comment]
Docs TODOs:
Telling new contributors about the loading bar and about how it's fake in the editor

Maybes:
Vending UI has keypad instead of buttons

**Comment by Bod9001** [comment]
//TODO Patch
    //UnityEngine.Events.UnityEvent, GetValidMethodInfo
    
    - mapping
    making new matrix
   spawn point setting /
   docking points  / 
Rotatable objects /
Quantum pad linking ( reuse multitool? ) /
renaming objects /
general mapping tool improvements
-perimeter for like walls
Mob spawn points 
 sprites for invisible items for mappers ( spawn point, random pool )  /
  auto saving!!!!
  change Variable client path not working /

**Comment by Bod9001** [comment]
disabling orbit when a tool is selected would be a godsend /

**Comment by Bod9001** [comment]
PDA on Cargo console authorise
being able to hack Console to bypass authorisation, ( maybe swap cables or something like that )

**Comment by Bod9001** [comment]
Occasional edge cases with high Momentum  /

**Comment by MaxIsJoe** [comment]
what does that mean

**Comment by Bod9001** [comment]
chat bubbles stacking, as in climbing the screen and maybe slightly faster /

**Comment by Bod9001** [comment]
mid round antagonistic 
e.g antagonist too far away, antagonist dead/AFK spawn ghost role if coastal not taken Make one of the station crew an antagonist

**Comment by MaxIsJoe** [comment]
> mid round antagonistic e.g antagonist too far away, antagonist dead/AFK spawn ghost role if coastal not taken Make one of the station crew an antagonist

This sounds like something that had an issue opened for it before but I can't recall its name

I think it was written by Jack and It talked about having like a system that checks the status of the station/round and change things around for antags.

**Comment by MaxIsJoe** [comment]
> This sounds like something that had an issue opened for it before but I can't recall its name

Found it and added it.

Due to it touching upon core stuff of unitystation, I've decided to list it under the considerations' category, as I don't believe it is a must-have and could cause unwanted game breaking bugs. 
If you feel otherwise, hit me up on our server.

**Comment by Bod9001** [comment]
More items should have prices for cargo to sell /

**Comment by MaxIsJoe** [comment]
> More items should have prices for cargo to sell

Added 👍

**Comment by Bod9001** [comment]
Relogging fix without restarting the client /

**Comment by Bod9001** [comment]
birdman850  Discussion
 Movement
 -mops sticky movement
 -Space movement polishing / Mostly done can be still buggy sometimes
-incorrect direction throw
 -increased power of throwing/Recoil
 -reset when reaching destination space /
 -regular movement glitching into walls client side
-reduce bounce and fly speed for players

**Comment by Bod9001** [comment]
player goals individual?
Highlight/tooltip 
for what each Interaction will do 
fix UI overlap
Light ambience
remember to do the changing movement speed while crawling /
generic tile map optimise Chunk list thing array , ues for nodes meta data and meta tile map + matrix.get< component> /
Engineering Goggles have no action button to activate T-Ray 
review maps for high pop and , looped maintenance and general big review of maps
Spaceship Ambience while moving /
highlight overwrites itself after a few seconds
cyborgs taking radiation damage, cyborg chassis damage

**Comment by MaxIsJoe** [comment]
This tracker's criteria clearly states that one line suggestions are automatically rejected.
Please explain what's the issue with all of these and what task needs to be done to fix them, rather than just using this as a personal notes tab.

**Comment by Bod9001** [comment]
https://discord.com/channels/273774715741667329/312454684021620736/1179016993366622238
add this todo

**Comment by MaxIsJoe** [comment]
> https://discord.com/channels/273774715741667329/312454684021620736/1179016993366622238 add this todo

Open a proper ticket for it.

**Comment by Fr-Dae** [comment]
> > [discord.com/channels/273774715741667329/312454684021620736/1179016993366622238](https://discord.com/channels/273774715741667329/312454684021620736/1179016993366622238) add this todo
> 
> Open a proper ticket for it.

https://github.com/unitystation/unitystation/issues/10204

**Comment by Bod9001** [comment]
player rotate is still broken after getting pushed by wind, funny angle walk, 
also may be  redoing spray will affect~
HOP console missing roles, /
Hop console missing colours /
job selection redesign needed
gizmos on moving shuttles
vending machine where you can load your own items
medical  healing gun
https://discord.com/channels/273774715741667329/312454684021620736/1211823731085942826
!game modes!
-body swapper , Who's Who! ( swaps bodies with people objective get to highest ranking person ) sounds fun and funny /
-poltergeist, a general annoyance, has to be trapped by salt lines, then can be forced into a body that can be Arrested
Strong grab
Whisper TTS/STT  <local speech to text and text to speech
Off-line mode not working
customisation genetics add / overwrite 
Everything having clicky buttons, 
spawn in sound for Crewe
syndicate bomb buff
traitor item access review
https://github.com/SpaiR/StrongDMM mapping uis, 
saving custom prefabs. as part of map? or separate files next to map
hide and show tile map layers /
Select a prefab to view all prefab that inherit from it in dev spawner  / ( technically still need to be done )
Device renamer + renaming player support
new matrix admin option
room gas setter needs to be not destroyed
DisposalTraversal , if you are In a pipe that gets deconstructed, technically you will be stuck?

**Comment by Bod9001** [comment]
admin tools / Round management;
VV Bounty manager needs to support item trait and Prefab Forever ID (Potentially mid round prefabs?)
player inventory examine, 
player teleport shortcuts, 
healing shortcuts
ACUs everyone gets access in atmospherics,
Chat entries not stacking
VV Search function inside of classes
set the iterations of rounding for device moving so 0.01, 0.1  /
rare bug that can cause you to be invincible? From bullets maybe, but not from space?? /
reactor stability?
"
paper
printers
also map feels unfinished
no cameras"
Time locks. Very simple 20, any role to get heads, 20 of any heads to get cap
clown emot , head expands like a balloon then explodes 
 admin goes being able to interact with stuff
 make asteroid mining more interesting so people use it instead of lavaland
 
 -closing tile changer menu removes full x-ray view.
-Grill doesnt delete when deleting a window. Have to go to grills section. (Minor issue)
-Lights leave metal and cables when pasted
- tile changer doesnt have those small reinforced windows. I copied em from the main station but i cant rotate em. 
- delete all selection would be good option to have.
-Cant rotate converyer belt with admin tools
-while placing tiles/walls. If you have action on (place) and you click on scroll wheel on the menu to scroll down/up it will place unintended tiles.
- Selecting  a large area and saving seems to be not possible.
- Tool that tells you what matrix you are clicking on would be good /
quick link reactionns!!!!
a delete area 
tokens for individual Server join <<<<<
clear moderation steps for servers on hub
an absolute bullet-proof ban system, 
Power/balancing gameplay?
Maps review ( maintenance and stuff ) 
and a few extra antagonists
Botanist additions
mining laval land (everything expect for ore gen
 Is static)
cloning balancing
credit?
dev docs!!!

**Comment by MaxIsJoe** [comment]
Updated the checklist to add a few more tasks

**Comment by AtnerNT** [comment]
Virology Foundations are in and the sickness check points can be marked off.
(Sickness vulnerability is controlled by the metabolism reaction set of a species. Disease growth reactions can be excluded from this list to gives certain species/mobs immunity to a disease)

**Comment by Bod9001** [comment]
xThe Finalist (well need to add to)
Maps review ( maintenance and stuff )
antagonists balancing (as in they appear in the games)
cleanup misinformation, start doing is about a month before
security checking on the docker builds
bug fixes and polishing
poltergeist?
RCON?< snep snep
UI Action icons don't disappear / ?
AI review (is ok, Though needs to fix camera When swapping bodies)
Viruses Balancing << /
Obliterate spam errors
Tooltips being stuck on /
ghost roles, being weird ? /
Review admin UI

trick issue escape shuttle doesn't synchronise properly sometime and then it's a bit buggy afterwards,
(getting hit by another shuttle seems to knock it into shape but then still buggy)

That translation system (To a basic level, ( The actual translation system itself should be fully implemented but Stuff looking into it will take ages so basic level for that , https://discord.com/channels/273774715741667329/668605946691452949/1427699138115665940)) / (Somewhat done)
Rotation issues on matrix for objects being the wrong way round / ?

shuttle movement polishing, moving diagonally when you're in between spinning mode and normal mode < ? ( Square station command, go maximum thrust (On the engine) go diagonal and turn the same time well Engine speed zero )

Jet packs being buggy (Not replicating inputs on client), /
holding onto moving slow matrixes, Smoother low-speed movemment, Maybe looking into gettting sstunned if you hiit by shutttle (And bounced off)

more fun random events (To keep things interesting, Getting sent cargo shuttle full of random stuff because NT needed somewhere to ddump it)(
Cargo shuttle random stuff /,
Spatial Distortion (Portals that go to random other portals) /
Random heart attack > 30 pop  /
Contaminated distro? 
Lost in transit disposal packages (Spits out random Items wrapped),
Unopened lockers contents are jumbled between different lockers ( previous station messed up cleaning ) nah
New joins end up in maintenance spawn ( We have somehow lost the arrival shuttle in a wormhole ) (  A pain because not everyone has maintenance........  )
Maintenance goblins have left more stuff in mainntenannce ( respawn mainteenance loot ) /
Random extra AI laws /
Pirates detected nearby the station.??
Killer Tomatoes have randomly mutated inside of Botany
)

Cloning still gives cursed items (Dropped from old body) Still
walk-through for more issues
AI Add cyborg console and laws inspection For cyborgs?

**Comment by Bod9001** [comment]
bug fixes and polishing (Always)



graphics/UX polishing (somewhat done?) < 1 /

strange seeds! random chemical with random percentage is enough to do <  /

(2.5 

shuttle polishing, 

spinney mode polishing, Stuck going diagonally,? (to do??), /
(if side thrust is on slightly it's enough to keep it going in spinney mode, even though the main thrusters are off) idk does it just rotate or is this fine?? IDK

performance for stations? ( need to make our own 2D circle overlap and bullet  ray cast physics with better bounds,  ) later on Task

rotatables on shuttles, observe shuttles when they arrive at station on client ??? , a lag spike while rotating can cause this
a shuttle in spinney mode doing a slow turn can stun lock you ( soft Lock OnRotate += KnockDownPlayers;) /
)



login flow < 3 {
+ steam integration
}
first time experience, Testing <<< Important 4{
Probably need to update the alpha text  /
Character job completion and descriptions
new character creator draft (as in polishing character created to be nice, but what can be improved about it?!) ( separate names for cyborgs and AI,
option for whether or not to reroll character if it's a ghost role/just rerol name
Wrong  character keeps from being selected in editor /
explanation of antagonist roles in character Creator
)

}

antagonists balancing < 5{
move of fixed order
 fix  changlings and xenos <<< 
blob needs mouseover text, for what stuff does  /
Blob resource generation needs to scale with pop (start ramping up 20+ max 60) /
fix blob cores not regrowing tiles naturally (fix to pop 10+) /
Wizard < needs testing (hummm, maybe a few more new spells ) /
test nuclear operative spawning ?? ( Seems to work okay ) /?
}

Maps review ( maintenance and stuff )  < 6 {
cigarette vendor 
maintenance loop
Department should have maintenance access apart from command?
Check Conveyor belts areen't busted
abandoned rooms in maints
Space to set up an alternative engine for  medium to Large maps
Escape pods
lawyers add court rooms
atmospherics not requiring access to set stuff on the main tanks

on lavalland 
potentially adding loot tendrils that spawned mobs in
}

mobs v2 maybe? (nah)

mapping tools still need polishing, Event linker. Custom CC shuttles is idk??

the odd bits and ends for thhe admmin  tools (invisible admin,  game mode,  subsystem, players joining and leaving lo

RCON? (remember to record round ID  because it gets lost every time it restart)< snep snep < 7

birdman850 Discussion < 8

cleanup misinformation, start doing is about a month before < 9

Performance review (Load test) < 10

o3o? 


==========================================

security checking on the docker builds

poltergeist? (nah, Can end up just being really annoying and then easily shut down with some salt, since you can throw damaging items around,  And then salt is really easy to make/dispense)

fiddly bugs
trick issue escape shuttle doesn't synchronise properly sometime and then it's a bit buggy afterwards,
(getting hit by another shuttle seems to knock it into shape but then still buggy)

Keep on losing hunger vision effects, is the synchronised affect client, I think it's an issue from possessing a different body then jumping back to the original body Where it is sending data from the body you originally possessed, That is overwriting the current state , May be fixed from fixing hunger being synchronised incorrectly??


Separate issue, shuttle movement
AI shuttle docked, But early launch considered it still moving, after setting off then proceeded to crash into station

Get stuck in disposals if it's a entrance bin, stuck inside of the bin and cannot move

Shuttle movement still weird if you go spinney mode then try turning left too much / (Thrusters need more power)

Electrical bugs out sometimes,
reactive supply SMES Outputs for voltage into line even though it's already satisfied resulting in 6kV when it should be 3kV
Unable to replicate but have come across in Rare games


sometimes, joining the game takes forever,  client has fine FPS so it's waiting from something from the server,
unable to replicate idk what it could be

Cloning still gives cursed items (Dropped from old body) Still (Sometimes??)

Noted an issue with bullet seeming to be travelling forever,  (In profile)
Note they are somewhat slow with the hotspot expose and
The Ray Cast line intersects Betteer box needs to be optimised a bit more now ( Some type of Simple BVH )

Shuttle on square station was rotated by 90° when trying to Doc,
( Shuttle has incorrect rotation but is accounted for in the guidance buoys , so maybe it's a leftover variable from previous round but I can't see anything? maybe from it docking with central command idk )


walk-through for more issues
