### ISSUE TITLE
Guide: Item basics and how they work in unitystation B: 35

### ISSUE THREAD

**Issue by DooblyNoobly** [unitystation/unitystation#1045]
# TODO

Create a guide that introduces new contributors on how items work in the codebase.

### Criteria:

 - [ ] Explain what a prefab is and quickly how to make one for people new to unity
 - [ ] Explain how to add a NetworkIdentity to the root of the prefab and what the NetID does
 - [ ] Explain the basic components that make up an Item (ItemAttributes.cs and CustomNetTransform.cs)
 - [ ] Explain how the pick up triggers work with the items
 - [ ] Explain how the CustomNetworkManager caches all of the prefabs that have NetworkID's on them on game start and why it does that (so each item has the same NetworkInstance Number across all clients)
 - [ ] Keep explanations short and simple (stick to the point, don't ramble)
 - [ ] Provide plenty of screenshots
 - [ ] Create the guide on the Wiki and ensure clear and readable markdown formatting is applied

Contributor who meets all of the above criteria will be awarded the $35 usd bounty on completion.

Post link to the guide here when it's done.

**Comment by NinjaDanz3r** [comment]
Working on it will post again when It's ready.
