### ISSUE TITLE
TODO: Atmos Implementation B: 300

### ISSUE THREAD

**Issue by krille90** [unitystation/unitystation#1097]
# Preliminary information

## Category
Feature Request

# Report
## Requested Behavior
Implementation of a Atmospherics Simulation for the Station.

Things that need to be worked out:
- [x] Handling of Atmos exchange between multiple matrices
- [x] Threading of Simulation to prevent lag
- [x] Storing Meta-Information of Atmos

**Comment by krille90** [comment]
I hope to make a merge by end of next week.

**Comment by DooblyNoobly** [comment]
Bounty of 300usd has been placed on this TODO. (updated from 200 to 300)

**Comment by DooblyNoobly** [comment]
Bounty increased from B200 to B260

**Comment by DooblyNoobly** [comment]
Bounty increased from B260 to B300
