### ISSUE TITLE
Develop and implement new 2D Lighting System B: 250

### ISSUE THREAD

**Issue by DooblyNoobly** [unitystation/unitystation#1181]
# TODO

Plan, develop and implement a new 2D lighting system

## Criteria

 - [ ] Remove all of the old Light2D scripts and lighting camera from the Camera prefab also remove the old code Snippets for the old system in the LightSource.cs script (SetLocalAmbientTiles()) 
 - [ ] Develop a new Lighting system that works well with the current FOV system
 - [ ] Make sure light does not seep through walls (if a room has no lights on and the door closes it should be dark inside that room)
 - [ ] Make sure lights are toggle-able using the light switch (all switches should already be hooked up and network enabled, use LightSource.cs for your light generation code)

Contributor will receive a bounty of 250 usd on a successful merge of a solution that completes all of the criteria above
