### ISSUE TITLE
TODO: NetTab GUI for GasContainer B: 150

### ISSUE THREAD

**Issue by krille90** [unitystation/unitystation#1454]
### Description
With the introduction of Atmos, the gas containers are also now functional in the way that you can open and close the valve by clicking on the container. This needs to be extended to a GUI, in which information of the gas are shown, where the release pressure can be changed and the valve can be opened/closed.

### Criteria

- [ ] Clicking on a gas container should open a GUI window
- [ ] Show information of the current content of the gas container, e.g. pressure, temperature, etc.
- [ ] Release pressure can be changed in the GUI
- [ ] Introduce a button to open / close the containers valve
- [ ] Any changes should be synchronized to other players

### Tips
Look at the class `GasContainer` to get a better idea:
https://github.com/unitystation/unitystation/blob/7728a5750651e761f5d495d38a8394abe98e6920/UnityProject/Assets/Scripts/Objects/GasContainer.cs#L10

**Comment by DooblyNoobly** [comment]
Bounty of 150 usd will be awarded to the contributor on a successful merge of all completed criteria above

**Comment by Carbonhell** [comment]
Gonna try to do it when possible

**Comment by DooblyNoobly** [comment]
All yours, changing to in progress

**Comment by NinjaDanz3r** [comment]
Talked with Carbonhell and I'm shanghaiing this task.
Quick mockup of the Valve:
https://imgur.com/Zp9bN7d

**Comment by NinjaDanz3r** [comment]
![gastankui mockup](https://user-images.githubusercontent.com/10200316/52434538-d6d07400-2b0f-11e9-8714-8c7759310730.png)
A quick mockup of the whole interface.

**Comment by Jibbajabbafic** [comment]
Remember, all this will need to be synced across clients using NetObjects (NetSlider, NetToggle... etc) so you might need to make a new one for the valve depending on how it's being implemented

**Comment by NinjaDanz3r** [comment]
I might as well do that, I think rotary controls might show up in a few other cases.
Also, new preliminary UI design according to input from Foma:
![gasui](https://user-images.githubusercontent.com/10200316/52522180-fe474e00-2c81-11e9-9a00-9ab172ca6af4.png)

**Comment by chairbender** [comment]
@NinjaDanz3r any update on this?

**Comment by fomalsd** [comment]
Need this rather sooner than later

**Comment by JacobSweeten** [comment]
Haven't contributed in a while, but I can give it a shot this weekend. I'll update you on whether or not it's feasible for me to complete when I get to look at it.

**Comment by JacobSweeten** [comment]
Can we get this marked WIP?

**Comment by DooblyNoobly** [comment]
done

**Comment by Jibbajabbafic** [comment]
@BeastKiller2013 any progress on this?

**Comment by JacobSweeten** [comment]
Sorry I got a little busy. Since I've made decent progress, I'll keep going probably tonight. I didn't realize it had already been 30 days.

**Comment by Jibbajabbafic** [comment]
No worries, just checking it's still being worked on. Glad you've made some progress with it, I look forward to seeing what it looks like!

**Comment by Jibbajabbafic** [comment]
@JacobSweeten still working on this?

**Comment by DooblyNoobly** [comment]
As we haven't heard anything from @JacobSweeten I'm taking this off InProgress. This bounty is up for grabs again and is high priority so I'm increasing bounty to 150

**Comment by chairbender** [comment]
I can give it a shot. The UI might not be spectacular but I can at least make sure it's functional.

**Comment by DooblyNoobly** [comment]
thanks, doesn't have to be a perfect work of art, just has to work.

**Comment by chairbender** [comment]
I've been working on this near constantly for the past 2 weeks, it's just been slow going because it's my first time building a UI in this game and there are elements in this UI which need to function quite unlike any of the existing elements.

**Comment by JacobSweeten** [comment]
@chairbender feel free to look at my repo fork or use the sprites I made.

**Comment by chairbender** [comment]
Just to track this, I've created a PR for what i have so far but I have quite a bit more to go:
Remaining work to be done:
* Sounds
* Flashing red status LED when super low (currently just shows solid red when low)
* Ability to drag window (disabled drag because it was preventing from using the wheel)
* Polish the drag interaction of the wheel (currently the rim changes color slightly when you click which looks weird, and it would be nice to add more of a signifier such as changing mouse icon when over the wheel or something)
* Potentially add client interpolation between updates of the internal pressure (currently it only updates each 0.5 seconds, client could interpolate these values so the numbers change more smoothly)
* Color variations and text changes for each canister (want to make it so I can also avoid having to create a separate asset for each canister background if possible, can probably do this using tinting)
* Connected / disconnected status indicator should update
* Click the release pressure to allow typing in the value
* Clean up remaining TODO comments
