### ISSUE TITLE
TODO: Ability to Stun and Cuff another player B: 220

### ISSUE THREAD

**Issue by DooblyNoobly** [unitystation/unitystation#1935]
# Description

We need to add the ability to stun other players and to cuff them to allow security to do their job. This TODO is to implement those abilities and to add/improve weapons to do the stunning.

### Stunning:
- Add the stunbaton as a prefab and allow the ability to turn it on or off.
- Update stunbaton sprites based on state
- Add the ability to stun someone if the baton is turned on and the user is set to help intent
- Allow stunbaton to apply melee damage to another player if user has intent not set to help (also stun if the stun baton is on)
- Stun the player using the functions already provided in RegisterPlayer.cs
- Finish the taser weapon and taser bullet prefab and allow them to put another player into stunned state when they are hit with the bullet
- Add all necessary soundfx for the stun weapons
- Test all the new features and weapons in multiplayer with a headless and two clients

### Cuffing:
- Add the cuffs item as a prefab
- Add the cuffs to the security job outfit so sec guards spawn with cuffs on spawn
- When clicking on another player with cuffs in hand play the cuffing sfx (make sure it plays to all other players in the near vicinity) and show the load bar over the player being cuffed (see wall deconstruction for an example on how the load bar works)
- Once the load bar completes then place the cuffs on the player by removing the cuffs from the users hand slot and destroying them via inventory manager
- Add a new state to the player by adding a flag that is easily accessible to most other player code and call it isCuffed.
- Stop player movement input from being allowed if this value is true
- Sync this value for the player to all clients, automatically enable a cuff overlay sprite when this Boolean is set to true and remove it when it is set to false
- Add a new sprite in the player sprites tree and develop the ability to show and update the cuffed sprite for each direction (this is mostly automatic, check the other sprites to get an idea on how to do it)
- Add the ability to uncuff a player by right clicking them and choosing uncuff (you will need to speak to the authors of right click menu on how to do this)
- Test the cuffing feature in multiplayer with a headless server and two clients

Contributor will receive a bounty of 220usd on a successful merge of a solution that satisfies the criteria above.

**Comment by JaytleBee** [comment]
I'll work on this one.

Btw. on /tg/ sec officers don't actually have tasers anymore but rather disabler beams.

**Comment by JaytleBee** [comment]
Making some good progress here, but it looks like the stun function in RegisterPlayer has a (kind of hilarious) bug:
![slippy baton](https://user-images.githubusercontent.com/7951887/59229332-5d8a8000-8bda-11e9-956a-0f56c3336de0.gif)

Not sure if this is known but I'll have a look at it once I'm done with everything else here

Another thing is that foma's(?) system for scraping items gives the stun baton the sprite that it should have when it's on a security belt. I'm still considering the best way to remedy this, let me know if you have any input

![image](https://user-images.githubusercontent.com/7951887/59229456-c2de7100-8bda-11e9-97fa-ed8482bb796a.png)

One last note: I feel like I remember the stun baton having a different inhand sprite when it's on, but I can't seem to find that one. I'll look into that too

**Comment by chairbender** [comment]
@JaytleBee FYI, in my current PR, Weapon is refactored quite a bit and now called Gun:
https://github.com/unitystation/unitystation/pull/1936

Not sure if that affects you, just wanted to give a heads up.

**Comment by fomalsd** [comment]
@JaytleBee I assume you pasted a hierarchy string into baton prefab's `ItemAttributes`? you can always assign values manually there, including inhand offsets (from `items_lefthand`/`items_righthand` spritesheets) and choose arbitrary world/inventory sprite
Also sliding bug is #1919

**Comment by JaytleBee** [comment]
Thanks for the heads-up, this will probably affect this a little bit though the changes required should be relatively simple. I'll continue work on the current branch and make the necessary changes once your PR is merged

**Comment by chairbender** [comment]
the PR is merged.

**Comment by JaytleBee** [comment]
Alright, I got a bit of a decision to make: The script that gets item and spite attributes from the scraped dm files works relatively well but has a few major visual bugs. Do I:

1) Not use it (items would work for now, but hierarchy would need to be set at a later date)
2) Use it (items would look kind of weird until the hierarchy thing is fixed)
3) Fix the hierarchy script (unsure how much work that would be, also probably better handled in a different PR)

Just to be clear, the visual glitches that occur when using the scraped data are
- No inhand sprite for handcuffs and taser(tazer?)
- Wrong sprite for the stun baton (fixes itself after you activate it)

**Comment by JaytleBee** [comment]
@DooblyNoobly Quick thing regarding the point "Add the cuffs to the security job outfit so sec guards spawn with cuffs on spawn": This isn't actually possible with the current system for job outfits. Currently, only unicloths can be spawned with that. I could hack it in so that it can spawn prefabs, but I think some consideration should go into refactoring the job outfit system.

**Comment by fomalsd** [comment]
don’t use hierarchy string if it works incorrectly, it’s totally optional
instead you can fill out all values manually

**Comment by DooblyNoobly** [comment]
@JaytleBee yep all good, don't worry about that criteria we can address it later. Make sure there are some cuffs in sec closets instead

**Comment by JaytleBee** [comment]
Quick progress update:
- Stun batons seems to work perfectly, I even fixed the weird sliding bug. One thing I noticed is the lack of a real system for alternating sounds. I went with the pattern the rustling sounds use for now (`"Sparks0" + UnityEngine.Random.Range(1, 4)`), but in the long term it might make sense to make a better system for this
- Tasers work, but the sprite doesn't update based on the amount of ammo left. I'm not sure whether to work on this since it isn't actually one of the criteria but seems like it might make sense to do it here
- Cuffs are in the game and can be used, cuffed players can't move at all (like specified, though it should be noted that this is different from tg where cuffed player can walk as long as noone is pulling them).

Things left to do:
- [x] Sprite to indicate that a player is cuffed
- [x] Uncuffing players
- [ ] Hunting for bugs
- [ ] Possibly making the taser gun's sprite change based on how much ammo is left

**Comment by JaytleBee** [comment]
Took a bit of time off but I put some more hours in and I finally got the handcuff sprites networked properly. Uncuffing players works only on server, I'll probably do that using a Command, like in PushPull.

I managed to fix the stun in RegisterPlayer, though I'll need to see how it works with slipping

**Comment by JaytleBee** [comment]
I'm terribly sorry about the delay, some life stuff is getting in the way (adding to that, a general lack of motivation, also I need to practice for a guitar gig). I will continue work on this soon.

**Comment by DooblyNoobly** [comment]
Thanks for the update, you're making really good progress. Any chance you could list out what is left to do?


On 27 Jun 2019, at 6:06 am, JaytleBee <notifications@github.com<mailto:notifications@github.com>> wrote:


I'm terribly sorry about the delay, some life stuff is getting in the way (adding to that, a general lack of motivation, also I need to practice for a guitar gig). I will continue work on this soon.

-

**Comment by JaytleBee** [comment]
There's an NRE on client when a taser bullet hits someone which I need to fix, and uncuffing doesn't work yet. Shouldn't be a lot of work, but the uncuffing is a bit of a drag to test (since I need to actually build the game) and I haven't done a lot of work with network messages yet.

**Comment by DooblyNoobly** [comment]
@JaytleBee  any progress update on this?

**Comment by JaytleBee** [comment]
I've made a bit of progress, I still need to fix a minor glitch and merge it

On a side note, I've been really unproductive lately for reasons I can't quite pinpoint. I'm sorry for the delay it's causing

**Comment by DooblyNoobly** [comment]
All good @JaytleBee just make sure you have something in by the end of the month as we are getting close to 0.4 beta
