### ISSUE TITLE
EPIC: Gas Pipes

### ISSUE THREAD

**Issue by chairbender** [unitystation/unitystation#2805]
## Description
This epic covers the implementation of atmospheric piping of gases. There are a lot of reasonably-sized tasks needed for this so I'm going to make this an epic with multiple, more achievable sub-tasks.

The ultimate goal is to have a system which allows using pipes to control the flow of gases and allow various atmos objects to hook into these pipes to perform various functions.

Subtasks

- [x] #2807 IF2 - add alt click to hand apply interactions (needed for being able to rotate pipes)
- [x] #2806 Laying Gas Pipes and Gas Canister Connectors - simply being able to place, rotate, and wrench them
- [x] #2808 Pipe Dispenser - so you can get pipes during the game
- [x] #2809 Pipenets + Gas Pipe distribution via canister connectors - build out the basic logic for how gas propagates through the pipes from connectors with canisters wrenched to them
- [x] #2810 Scrubber piping - allow scrubbers to pull gases into their pipe
- [x] #2811 AirVent piping - AirVents distribute their gases from their pipe
- [x] #2812 OutpostStation pipenet mapping - remap the station so that the scrubbers / airvents are set up and hooked up to pipenets.
- [ ] TODO: Other atmos objects, see https://tgstation13.org/wiki/Atmospherics_items

**Comment by corp-0** [comment]
closing since piping work is done and this issue referes to an old task that is not relevant anymore.
