### ISSUE TITLE
Examine system - Extra work needed

### ISSUE THREAD

**Issue by drneuris** [unitystation/unitystation#3271]
#3179 implemented basic examine functionality, but it needs more work to be effective.
#2340 and #2643 directly depend on this, and should be fixed in one pr.

I'll be working on it so this is more of a tracker for stuff to work on than an actual issue. Let me know if this doesn't belong to an issue.

- [x] ~~There is a pretty big limitation right now in how Equipment doesn't have access to ID slot because players are not observers of the ID slot by default.~~ Solution: Add a VisibleName somewhere in playerscript that is updated by server on equipment change (pickupable OnInventoryMoveServer calls refreshvisiblename on playerscript) and will hold logic to check face items etc (already submitted PR for this as it's kinda disruptive)
- [x] Make items in inventory/ui examinable
- [x] adding functionality for in-progress construction to provide feedback as per #2340 (reinf wall and computer construction) - very easy, eta: soon
- [x] tile based examine implementation
- [x] Add Examine() to guns and mags
- [x] inclusion of right click items logic to streamline examine behavior
- [x] refactor existing OnExamine behaviours to be compatible/get rid of it entirely

All of the above has been merged in #3333 

- [x] Let examine get clothes on people at very least (in itemmanager probably have an array of named itemslots in to collect and send) Done in #5130.
- [x] add more medical flavor (he has severe/moderate bruising! he is bleeding! he has minor burns. etc), limb damage - very easy, eta: soon
- [x] Add itemtrait for masks/helmets (something like ObscuresFace) to be checked for showing/hiding name when ID not on belt (for antags). Partially done in #5130. Slots are obscurable.

To be moved to their own issue:

- [ ] At least an initial implementation of security checks / visibility checks (also on the client side to avoid sending unnecessary messages)
- [ ] Let server calculate distance between interactor and interactee to allow distance based information details (don't want to see small cuts on people if 10 tiles away)

Logistical/documentation tasks:
create .md page with basic details to allow anyone to extend

**Comment by daalta** [comment]
https://github.com/unitystation/unitystation/issues/3356 would might pave the way for displaying examine messages next to the examined object.

**Comment by drneuris** [comment]
Yeah that's pretty inviting considering chat clutter! Would be easy to change addexaminemessage to make a bubble instead of sending to chat, or make a different function. Will follow the developments

**Comment by PerfectTangent** [comment]
last required point was added in #5877, closing.
