### ISSUE TITLE
Disposals Issue and features B:150

### ISSUE THREAD

**Issue by NoooneyDude** [unitystation/unitystation#4654]
Known issues from #4524.
### Known issues

- [x] fix #6568.
- [x] 22. Items ejected from a disposal pipe terminal sometimes permanently spin, as described in issue #5551.
- [x] 3. Constructed pipes with non-standard grey colour return to default grey when welded to form a tile.
- [x] 4. Sometimes items can be ejected at a strange angle.
- [x] 13. Players are exposed to vacuum when traversing disposal pipes that are in space.
- [x] 14. Disposal machines do not use power from APCs.
- [x] 15. Disposal virtual containers can be seen by players if they bring up the context menu for the same tile the container is on. This is issue #4619.
- [x] ~~16. Comply with requested changes in #4524.~~ _**Partially addressed by PR #5786.**_
- [x] 7. ~~Dropping items while in a disposal instance does not add them to the disposal virtual container, and so they are lost to the void.~~ Items dropped while in a disposal instance are invisible once ejected.
- [x] 8. Coloured machine does not apply to overlays (bin overlay spritehandler).
- [ ] 9. Tiles aren't actually broken when items are ejected from pipe end - the update is merely visual.
- [x] 19. DisposalVirtualContainer can be spawned via the dev spawner menu.
#
### New features
- [x] G. Dump the contents of the trash bag into the disposal bin without dumping the bag itself, as described in #4938. This should probably be a property of the bag and not the bin.
- [x] H. Disposal bins should actually take in ambient air, store it, and send it with the disposal traversal. Lungs inside the instance should then breathe from this gas mix. Should solve issue part 13. in the process.
- [x] C. A tooltip for the pipe dispenser's dispensables would be nice, too.

 #
- [x] **Disposals crawling** - When a player enters a disposal pipe system, they should be able to stop flowing along the pipes by pressing the resist key. After struggling for a period of time, they will stop moving with the flow and instead be able to crawl through the pipes in any direction they want to. 

They should also be able to enter disposal pipe openings in a similar manner to disposal bins to initiate crawling at any time they would like, allowing them to navigate pipes in a similar way to small creatures vent crawling. They should also be able to crawl out of disposal pipe openings and disposal bins to get free of the system. 

Disposals crawling will greatly expand the possible applications of the disposals system and add an effective counter to being trapped in disposal pipe loops set up by griefers.

**Comment by PerfectTangent** [comment]
The remaining problems and features listed in this issue are being promoted to bounty status with a value of 100 USD. To fulfill the bounty, one must complete all of the remaining listed problems and features.

**Comment by PerfectTangent** [comment]
An additional feature request has been added, and the price for this bounty's completion has been increased to 150 USD.

**Comment by PerfectTangent** [comment]
oops don't think this was meant to be closed, just a prefix mistake.

**Comment by dapocalypse** [comment]
22. is fixed

**Comment by dapocalypse** [comment]
![Screenshot (39)](https://user-images.githubusercontent.com/22781705/150696825-2304e1b6-7a24-457e-bdc9-a641357632be.png)

Unable to replicate 3.

**Comment by dapocalypse** [comment]
I've been working on this for a while and I've been unable to replicate 4

**Comment by MaxIsJoe** [comment]
I claim over this bounty by introducing #9778

Now, I do have some notes and questions:

1.  #9778 fixes the first issue.
2. second issue (22?) has been already fixed long ago with the movement update.
3. 4th issue is odd, objects do not eject at any strange way or direction so i assume this was also fixed in the movement update by bod?
4.  #9778 makes bins use APCs and power
5. 16 isn't clear, can you explain to me what needs to be complied with exactly?
6. 9 and 7 aren't clear, can you give examples and how to replicate them?

**Comment by MaxIsJoe** [comment]
still waiting for answers :)

**Comment by MaxIsJoe** [comment]
number 15 was apparently fixed at some point, so we can ignore that.

#9822 should wrap up the bounty, will need someone to review this once it is merged.

**Comment by corp-0** [comment]
completed by #9822
