### ISSUE TITLE
Current Atmos Pipe Issues

### ISSUE THREAD

**Issue by ThatDan123** [unitystation/unitystation#4882]
List of current known issues with the atmos pipes:

- [x] NRE errors on round restart, can be reproduced in editor. EDIT: saying this is fixed for now as its only happened once after a fix. Issue is #4925 
- [x] Scrubbers dont filter, they just try to keep the target pressure and dont care about which gases they do it with. This is needed to be fixed to stop plasma floods filling the station. Or at least would be nice to have.
- [x] Mixer UI close button doesnt work
- [x] If #4886 is merged then the filter UI needs updating for all the gases. Added NO2 filter, other new gases havnt been added
- [x] Canisters dont seem to be filling up when connected to a gas connector, yet the gas still disappears.
- [x] Wrenching/Unwrenching meters doesnt work
- [x] Vents and Scrubbers are not animating, not necessary but would be nice to have
- [x] Pumps start with the On sprite instead of Off.
- [x] Wrenching and unwrenching pipes seem bugged on staging.
- [x] Unwrenching should not be instant if pressure is high to stop accidental removal
- [ ] ~Unwrenching pipe seems to not update atmos correctly?~
Picture was unwrenching pipe with plasma in it.
![image](https://user-images.githubusercontent.com/56727168/90330755-3f22d000-dfa7-11ea-8ecd-20f7a5674411.png)
I couldn't reproduce this. Seems fine now.
- [x] Need the ability to rotate pipes, I think nooney added a right click action to rotate in another PR.
- [x] ~Atmos analyser needs to be made clearer~, also doesnt show which type of gas in pipe:
![image](https://user-images.githubusercontent.com/56727168/90330846-cec87e80-dfa7-11ea-9808-0fa7446be1e8.png)
While you still can't use the analyzer on pipes, the text was updated to 
![new analyser text](https://user-images.githubusercontent.com/6926225/117782778-101b5f80-b296-11eb-9c21-4877f42678c8.png)
- [x] You can see the pipe direction when vents/scrubbers have a floor below them, not desperate to fix. Will probably need to separate the pipe sprite from the object, then have the pipe sprite on the underfloor layer?
![image](https://user-images.githubusercontent.com/56727168/90331024-7abe9980-dfa9-11ea-8204-aebd53523d89.png)
- [ ] No idea how easy this would be but a Test for the pipe net being fully connected, just in case of unconnected pipes when mapping. Also for unconnected vents/scrubbers (excluding self sufficient ones) Give coordinate instead of object name for if wrong, so it is easier to find the error.
- [ ] #4701 needs to be fixed too. Eg a tool to reorder the layers in the editor, so it goes disposals, pipes, wires.
- [x] The atmos devices, eg vents/scrubbers need to be moved to unshootable machine layer.
- [x] Not desperate but adding the remaining gas types, or at least NO2 to complete the atmos filter system would be nice. NO2 has an overlay light plasma.

**Comment by NoooneyDude** [comment]
I'm not sure if I agree with the non-instant wrenching. That's not how it is in /tg/, unless the pipe pressure exceeds 2000 kPa. Or is the accidental unwrenching more of an issue here?

**Comment by ThatDan123** [comment]
Making it take time if pressure is high is a good idea

**Comment by NoooneyDude** [comment]
Oh, the right-click rotate action is provided by the PlayerRotatable component, just need to add that - assuming unwrenched pipes are prefabs.

**Comment by ThatDan123** [comment]
Theres a couple of Pipe NREs/Errors that happen on round restart.

```
MissingReferenceException: The object of type 'Matrix' has been destroyed but you are still trying to access it.
Your script should either check if it is null or you should not destroy the object.
UnityEngine.Component.GetComponent[T] () (at <1245d947a91b4a14b7c7e2c7335512b2>:0)
Matrix.get_MetaTileMap () (at Assets/Scripts/Tilemaps/Behaviours/Layers/Matrix.cs:18)
Matrix.IsEmptyAt (UnityEngine.Vector3Int position, System.Boolean isServer) (at Assets/Scripts/Tilemaps/Behaviours/Layers/Matrix.cs:199)
MatrixManager.AtPoint (UnityEngine.Vector3Int worldPos, System.Boolean isServer) (at Assets/Scripts/Managers/MatrixManager/MatrixManager.cs:202)
MatrixManager.ReagentReact (Chemistry.ReagentMix reagents, UnityEngine.Vector3Int worldPos) (at Assets/Scripts/Managers/MatrixManager/MatrixManager.cs:458)
Pipes.PipeData.SpillContent (System.Tuple`2[T1,T2] ToSpill) (at Assets/Scripts/FluidPipe/PipeData.cs:209)
Pipes.PipeData.OnDisable () (at Assets/Scripts/FluidPipe/PipeData.cs:186)
Pipes.MonoPipe.OnDisable () (at Assets/Scripts/FluidPipe/MonoPipe.cs:47)

```

**Comment by corp-0** [comment]
>  NRE errors on round restart, can be reproduced in editor

that one should be done

**Comment by ThatDan123** [comment]
Errors still occur

**Comment by ThatDan123** [comment]
Seems the NRE errors can still happen but isnt every round restart now which is good.

**Comment by corp-0** [comment]
we good with this issue now?

**Comment by PerfectTangent** [comment]
are we?

**Comment by PerfectTangent** [comment]
The remaining problems in this issue are being promoted to bounty status with a value of 80 USD. To fulfill the bounty, one must complete all of the remaining listed problems. This includes doing #4701.

**Comment by PerfectTangent** [comment]
removing the bounty on this issue.

**Comment by corp-0** [comment]
This list is hella old. If we want to keep doing some of the missing tasks here, make a new issue for every indivial one we care about. Closing.
