### ISSUE TITLE
First Implementation of the Wizard Antagonist B : 100

### ISSUE THREAD

**Issue by PerfectTangent** [unitystation/unitystation#5160]
## Description
Wizards of the Wizard Federation are a classic round antagonist who's signature feature is casting spells for fun and profit. They spawn inside a special wizard's shuttle and gain a spellbook with which they can memorize a variety of spells to assist in completing their objectives.

In /tg/, wizards have a few unique objectives, but the majority of them are exact copies of traitor objectives, with the exception of never having to escape on the evac shuttle (for obvious reasons). They have an allotment of 10 spell points to spend on spells from their spellbook. Some spells require the wizard to be wearing their wizard's robes to cast and others may be cast without the wizard's robes.

The intention is to make the wizard a playable antagonist in time for Spooktober this year (roughly a month from now). This does not mean that ALL things on this list must be completed by then, only enough to make the wizard _playable_ (and prefereably not broken or imba).

## Important Features:

- [x] A spell memorization system and spell points.

- [x] Wizard's robes and hat functionality.

- [x] An initial list of 10 spells to learn and cast.

- [x] The Wizard's ship mapped and added to scenes.

- [x] The teleportation scroll that the wizard uses to board the space station.

## Secondary Features that would be awesome to have:

- [x] Wizard Apprenticing - bestowing limited spellcasting to a willing apprentice. 

- [x] At least two Wizard Artifacts.

- [ ] A variety of wizard robes to choose from for customization purposes.

- [x] Spawnable and/or discoverable single-use spellbooks to grant magical power to non-wizards.

## A proposed list of spells that could be (more-or-less) easily implemented:

- [ ] Magic Missile 
- [x] Force Wall (already half way implemented with the mime)
- [x] Teleport
- [x] blink
- [ ] Repulse
- [x] Lightning Bolt
- [ ] Ethereal Jaunt
- [x] Lesser Summon Guns
- [x] Fireball
- [ ] Knock
- [ ] Smite _or_ Blind (Smite is a classic wizard spell, but it's also a bit lame and there would not be very many counters to it at the moment, so I suggest Blind as an alternative)

**Comment by Bod9001** [comment]
added bounty thanks from Jack Trachea for the direct donation

**Comment by Bod9001** [comment]
asked in DMs who'd be interested in doing it NoooneyDude, said they would be good for doing it

**Comment by NoooneyDude** [comment]
### Development status
Ordered chronologically.

#### Stage One - PR #5274
- [x] Gamemode, antagonist, occupation populator SOs and player antagonist preference
- [x] Wizard base subscene (for the development environment only)
- [x] `Scroll of Teleportation`
    - [x] UI
    - [x] Teleporting
    - [x] Animating
- [x] `Book of spells`
    - [x] SOs for categories and entries
    - [x] UI
    - [x] Assigning/spawning
        - [x] Drop pods
- [x] `Teleport` spell
- [x] `Wizard Hardsuit` artifact

#### Subsequent PRs
- [x] `Lesser Summon Guns`. Added in PR #5279
- [x] `Blink`. Added in PR #5286
    - [x] Random teleportation
- [x] `Fireball`. Added in PR #5341
    - [x] Aimable actions
    - [x] Incendiary and explosive projectiles
- [x] `Forcewall`. Added in PR #5426.
- [x] Spell books (fireball, forcewall and as the applicable spells come)
    - [x] Simple book reading
- [x] Random initial spells
- [x] Wizard robe functionality
- [x] `Lightning Bolt`. Added in PR #5561.
    - [x] Electrical arc effect
- [x] Magic mirror
- [x] Upgradeable spells. Added in PR #5599.
- [x] `Instant Summons`. Added in PR #5610.
- [x] `Summon Guns` and `Summon Magic` rituals
- [x] `Contract of Apprenticeship`
    - [x] Ghost Role system
        - [x] Backend
        - [x] UI
- [x] New spell `Balderdash`. Added in PR #5766.
== issue complete ==
- [ ] `Ethereal Jaunt`
- [ ] `Singularity Hammer`? (as per issue #5278)
- [ ] Wizard death ends gamemode?
...

**Comment by PerfectTangent** [comment]
completed with #5766. Moving remaining features to #5291
