### ISSUE TITLE
Wizard antag stage 2 features

### ISSUE THREAD

**Issue by PerfectTangent** [unitystation/unitystation#5291]
## Description
This is a follow up to issue #5160. Once the wizard's core features have been added, it would be nice to start getting into the more peripheral features of the wizard. This list is not to make the wizard feature complete, but to get a good sampling of all the main features of wizards and the magic system in general. These additions will greatly increase the different ways that wizards can be played; blaster wizards, artifact wizards, the elusive stealth wizard, etc.

## Additional Spells

- [ ] Magic Missile
- [ ] Knock
- [ ] Smite
- [ ] Repulse
- [ ] Blind
- [ ] Ethereal Jaunt
- [ ] Spell Cards 
- [ ] Soul Tap
- [ ] Lesser Summon Bees
- [ ] Stop Time
- [ ] Rod Form
- [ ] Arcane Barrage
- [ ] Charge
- [x] Thrown Lightning (added in #8579)
- [x] Instant Item Summons (added in #5610)

## Artifacts

- [ ] Staff of animation: brings any item that can be picked up to life. animated objects attack anyone except the caster. Objects with a heavier weight deal more damage and larger objects have a higher health pool before reverting to their original lifeless state.
- [ ] Staff of the Locker: traps the target in a welded locker; Most funny.
- [ ] Staff of Healing: Heals the target of the staff.
- [ ] Mjolnir: hits hard, stuns, and launches targets away from you. _B O N K._
- [ ] Singularity Hammer: a discussion was held about reworking this item to make it more independent from Mjolnir. See issue #5278
- [ ] Scrying Orb: Grants the wizard limited x-ray vision and allows the Wizard to ghost around like an admin to scout, then return to their body. 
- [x] Spellblade: has a high attack deflection chance and shoots magic bolts. Good at dismembering targets. (added in #8584)
- [x]  Contract of Apprenticeship: summoning a ghost as an apprentice with limited spellcasting who is sworn to do the wizard's bidding. (added in #5700)
- [x] Summon Events/Rituals (added in #5624)

## Wands

- [ ] Wand of Death: instantly kill the target.
- [ ] Wand of Healing: heals a given target. Can also act as a defib and bring a dead target character back to life.
- [ ] Wand of Fireball: behaves exactly like the fireball spell
- [ ] Wand of Teleportation: randomly teleports the target. Similar randomness to the blink spell, but has a small chance to send the target to specific locations, such as lavaland.

## Other features

- [ ] The Chaplain and ERT Chaplain should be provided with inherent damage resistance to spells and immunity to spells cast upon them while having the null rod in their inventory.
- [x] A variety of wizard robes to choose from for customization purposes. (added in #8586)
