### ISSUE TITLE
Pogstation needs to be refurbished and put back into rotation.

### ISSUE THREAD

**Issue by PetMudstone** [unitystation/unitystation#5543]
### Description
For roughly two months now Pogstation has been left un-updated after atmos pipes and other changes. Its absence is felt by everyone, as there are only two medium to high population maps to go around right now. It appears that many players are clamoring for Pog's return.

Pog needs the below fulfilled in order to be made ready:

- [x] Movement of Pog's syndicate shuttle to a new scene, as stated in #4919.

- [x] Addition of atmos pipes and a working pipe network, as stated in #4874.

The two below would be nice for Pog, but are not strictly necessary.

- [x] Addition of a fugitive spawnpoint, as stated in #5346.

- [x] Adjustment of station lights, as stated in #4849.

**Comment by NoooneyDude** [comment]
All points except for the final one were completed by PRs #5635, #5670 and #5743. Is the lighting still in need of adjustment? In either case, closing this issue in favour of #4849.
