### ISSUE TITLE
Matrix bugs Bundle Bounty B: 80 total

### ISSUE THREAD

**Issue by PerfectTangent** [unitystation/unitystation#5818]
This is a bounty that encompasses fixing multiple bugs involving station matrixes. Each issue can be completed individually for 1/4 of the total bounty (20.00 USD). See each individual issue for details.

### Requirements

- [x] fix issue #5685 - **_fixed by #5974_**

- [x] fix issue #5690 - **_fixed by #5978_**

- [x] fix issue #5676 - **_fixed by #5976_**

- [ ] fix issue #5553

**Comment by PerfectTangent** [comment]
Given Aranclanos's investigations, it's possible that the last issue in the bundle is simply unfixable, so, this bounty bundle is being closed.
