### ISSUE TITLE
Bugs and issues with the Ancient Engineer ghost role and Scene

### ISSUE THREAD

**Issue by PerfectTangent** [unitystation/unitystation#5947]
Now that the Ancient Engineer has been merged, it can be properly tested. Several issue has been discovered with the scene that must be addressed before it can be properly played. The mapping issues in this serve as a to-do list for myself, but several of these are bugs with the ghost role system or the role itself.

### Issues found so far that must be fixed or mitigated with the _ancient station scene:_

- [x]  Wires cannot be laid onto base floors _unless the basefloor already has wires on it._ This is a very peculiar issue and I'd love for someone else to try to reproduce this. **_mitigated but _not fixed_ with #5983_** 
- [x]  space wind is a big issue with the destroyed hallways readily venting things into space once the player begins navigating the station. Perhaps reduce the number of damaged sections of the station from 5 to 3. **_fixed with #5983_** 
- [x]  the map could use more basic materials (metal, glass, gold, etc.). **_fixed with #5983_** 
- [x]  the shuttle needs RCS thrusters and collision detectors.
- [x] Add some plant seeds so the Ancient Engineers can grow their own food **_fixed with #6114_** 
- [x]  fix the scene ID isue described in #5958. **_fixed with #5972_** 
- [x]  add underFloorlayer script to the under floor layer. **_fixed with #5972_** 
- [x] Fix hostile mobs being non-violent. **_fixed with #5966_** 
- [x] ~doors do not work properly and must be replaced with old doors~ actually it's probably best to fix the new doors rather than replace them. **_fixed with #6302_** 

### issues found with the implementation of the _Ancient Engineer Ghost Role:_

- [x]  The Ancient Engineer option in the Ghost Role menu does not seem to update the available slots after a player picks the role. It may be a cosmetic issue only or it might not be properly limiting the number of players that can pick the role. - **_fixed with #6666_**
- [x]  The Ancient Engineer has the wrong populator, spawning with normal Engineer gear rather than the Ancient Engineer gear. **_fixed with #5983_** 
- [ ]  Upon starting a new round, the old Ancient Engineer Ghost role option was still available in the ghost role menu _in addition to the new one added at round start,_ meaning there were 2 Ancient Engineer slots in the Ghost Role menu.

**Comment by corp-0** [comment]
Last one is weird because it should clear the list every round start, then add the alwaysAvailable roles

**Comment by PerfectTangent** [comment]
yeah, it is weird. I was able to get the role from either of them, as well 
![Screenshot 2021-02-05 084715](https://user-images.githubusercontent.com/68730437/107041727-d9154980-678e-11eb-88df-f3a4efe23cd7.png)

**Comment by NoooneyDude** [comment]
> Last one is weird because it should clear the list every round start, then add the alwaysAvailable roles

Hmm. We probably need to tell the ghost role UI to clear the list or something - but then I am confused as to why you can still sign up on the old role..

**Comment by NoooneyDude** [comment]
Ah, I see. Does the ghost role uint ID get reset to 0 after a round? Can look into using a better form of ID and also clear the ghost role UI on round restart.

**Comment by ThatDan123** [comment]
~Ancient Station shuttle needs to have the underFloorLayer script on the under floor game object, currently just has the layer script, this is causing an NRE~ Fixed in #5972

**Comment by ThatDan123** [comment]
Ancient Station uses the new doors which have bugs, so will need replacing

**Comment by NoooneyDude** [comment]
> Upon starting a new round, the old Ancient Engineer Ghost role option was still available in the ghost role menu in addition to the new one added at round start, meaning there were 2 Ancient Engineer slots in the Ghost Role menu.

Was this fixed by #6490?

**Comment by PerfectTangent** [comment]
I cannot reproduce the last issue, so it probably was fixed by #6490. Thanks to @PetMudstone's #6863, this issue can be closed.
