### ISSUE TITLE
Add the Mining Equipment Vendor, Ore box, Ore Redemption Machine, and basic money tracking and spending on IDs bounty B:65

### ISSUE THREAD

**Issue by PerfectTangent** [unitystation/unitystation#6151]
### Description

**This bounty call for a rework of the implementation of the Ore Redemption Machine (ORM) to work more like how it does in /tg/, as well as the addition of basic tracking of labor points and credits on crew IDs, and making the Mining Equipment Vendor charge labor points for the items it offers.**

Ore boxes are fairly simple. When you drag them over ore on the ground, the ore is picked up by the box. Players can also directly place ore inside. There also needs to be a way to check how full the ore box is (this could be done by examining the the box, but it possibly also be given a resprite that gives the box some kind of cool meter that fills as the box is filled up)

You should be able to drag an ore box in front of the ORM and they will automatically be loaded into it, You should also be able to dump your satchel into the ORM by clicking the ORM with the satchel in the active hand or while activating the satchel while standing next to the ORM.

When ore is added it adds unclaimed credits to the machine, which can be claimed by inserting an ID and selecting "claim". You'll need to add a way to store mining credits on the ID card (this can just be a server-side only miningCredits field on the IDCard component).

The UI itself allows you to enter a number of sheets to print of a given material, provided that you have sufficient ores for it. It also allows smelting sheets if you have the right combination of materials for them. The different sheet materials which it can spit out should be separate prefab variants.

Crew IDs need to be able to track, receive, and spend labor points and credits. Credits do not need to do anything in this bounty, the framework simply needs to be put in place. Labor points should be able to be spent in the mining equipment vendor.

The Mining equipment vendor needs to be reworked to allow it to accept crew IDs and let crewmembers spend labor points on equipment listed within it. 

### what is needed to fulfill the bounty

- [x] Add the ore box - **added in #6265 and #6268** 
- [x] Rework the Ore Redemption Machine to work like how it does in /tg/ - **added in #6227 and #6243**
- [x] Add basic credit and labor point tracking and spending to crew IDs - **added in #6251** 
- [x] Add labor point prices and purchasing to the mining equipment vendor - **added in #6251** 

### Notes

Additional info about ORM and other mining stuff can be found here: https://tgstation13.org/wiki/Shaft_Miner

You can see it in action here:
https://youtu.be/KOtfRZt6F3s?t=1148

Mining equipment vendor can be seen briefly in action here: https://youtu.be/KOtfRZt6F3s?t=1255

**Comment by Aranclanos** [comment]
Ill tackle this one, but im unsure about the separation of credits and labor/mining points

**Comment by PerfectTangent** [comment]
we want to track 2 currencies to begin with on crew IDs. One is money, to be spent on vending machines and such. The other is Labor points, which are used by miners to purchase mining equipment from the mining equipment vendor, and for prisoners to work off their imprisonment.

**Comment by Aranclanos** [comment]
#6265 still doesnt have all ore box features at the moment

**Comment by PerfectTangent** [comment]
this bounty has been completed.
