### ISSUE TITLE
Health rework issues live on staging

### ISSUE THREAD

**Issue by Aranclanos** [unitystation/unitystation#6195]
WHEN YOU CHECK SOMETHING OFF REFERENCE THE PR THAT FIXED IT.

Roughly ordered by priority.

## BUGS

- [ ] ~~the bright red vision constricting crit overlay persists after death sometimes.~~ - needs reproduction, existed before health
- [ ] ~~bodies are getting stuck in place after death, becoming undraggable.~~ - existed before health
- [ ] when you are stunned or slipped there's no body drop sound.
- [ ] on spawn, initial movement is slow (as in #6552)
- [ ] moth wings and antenna are not rendering in the correct spot from certain sprite facings, both in the character customization window and in game. Sometimes they are completely absent. -  **Progress made with #6329, #6333, and #6361, but still not fully fixed.**
- [x] excessive blood production (see #6493) - mysteriously fixed, likely by #6634 and #6620
- [x] Welding things with welders is causing people to suffocate to death, even with internals, _possibly, **needs reproduction.**_. wtf, man. - **Fixed with #6470** 
- [x] when examining a character, the text is not describing whether they are hurt or dead. **fixed by #6519**
- [x] health analyzer doesn't track oxyloss damage anymore - **presumably fixed by #6471**
- [x] the character preview in the character selector is not rendering pixel perfect. - **fixed by #6440 and #6512** 
- [x] character sprites in the character customization window may not be rendering pixel perfect - **fixed by #6313, #6440, and #6512**
- [x] Some interactions still use the old LivingHealthBehaviour to apply damage, see in the comment below for more info
- [x] health doll doesnt update?
- [x] players spawning with a different character sheet - **possibly fixed with #6202**
- [x] hair names dropdown list having long names, ex: "head hair_hair_bob" **Fixed by #6356**
- [x] Human Lungs gasps! message - **Fixed with #6196**
- [x] o2 alert, pressure alerts and temperature alerts dont show up
- [x] ghosts are invisible - **Fixed with #6312**
- [x] arms and hands dont have cloth sprites when your character is looking to the sides - **Fixed with #6207**
- [x] human skin can be any color. - **Fixed with #6282**
- [x] lizard tail is not correctly coloring to match the body - **Fixed with #6357**
- [x] NPC mobs can't seem to be hurt or hurt plays in return - **Fixed with #6206** 
- [x] brains have no examine text - **Fixed with #6301** 
- [x] players are unable to leave their bodies after death in some instances (possibly related to admin smiting)
- [x] When you perform CPR it does it to the selected body part, eg you can perform CPR on eyes - **Fixed with #6264**
- [x] Using internal tanks (including oxygen ones) makes you seemingly die of oxygen loss. **Needs reproduction.**
- [x] player bodies are sometimes only showing as floating human skulls. This appears to be a client by client problem. **Needs reproduction.**
- [x] Right click rotate only rotates body parts
- [x] when you try to get up after crawling, it displays the same text "You try to lie down." - **Fixed with #6395**
- [x] Action text rotates with the character when they are crawling. Sometimes it stays rotated after standing up. - **Fixed with #6387** 
- [x] if someone puts you inside a locker while you are crawling your client shows that you are standing but to everyone else you are crawling. When you stand up you stay rotated but are able to run at normal speed. **Fixed with #6410**
- [x] While crawling, you cannot pass through tiles that contain objects, including ones you should be able to such as light fixtures **Fixed with #6327**
- [x] bruise packs and ointment do not work. - **Fixed with #6301** 
- [x] if you try to crawl and emote at once, you're gonna have a bad time. - **Fixed with #6387** 
- [x] switching to a different bodypart once you cut open one doesnt switch out the menu

### Bugs that have not been reported or reproduced in a while (might be a non issue)
- [ ] some players have reported moving at full movement speed after going into crit.
- [ ] slipping, tazing, stunning, dying, or any kind of player rotation besides crawling does not work reliably.
- [ ] once you have started resting in a bed, you cannot unrest anymore. Reported a bunch, but, **needs reproduction.**

## FEATURES TO ADD
- [ ] the surgery menu is not reliably showing all surgery options.
- [ ] it is unclear what stage of an ongoing surgery you are at if you have to pause for any reason.
- [ ] defibrillators lack player feedback for their actions.
- [ ] buckling into a bed should count as crawling/resting for the purpose of getting the benefits of doing so. Currently, one must lay onto a bed or operating table and then initiate crawling to allow surgery to be conducted.
- [ ] plasma is no longer dangerous to breathe in by itself and needs to be reimplemented. Gasmasks also need to be reimplemented (see #6109)
- [ ] Reimplement Harvesting (what does this mean?)
- [x] Convert all mobs over to the new health, At the same time delete all old mob prefabs and redo them as prefab variants (see #5325)
- [ ] gibbing from attacks and explosions
- [ ] Add dusting, alternative to gib which turns you into ash and destroys items (will need a way to stop important items like nuke disk from being destoryed)
- [ ] Electrocution overlay
- [ ] Clean up electrocution code in the playerHealthV2
- [ ] wall-mounted defibrillators 
- [x] removal of brain or head should result in death (lol) - **added in #6610** 
- [x] Readd blood effects - **added in #6205**
- [x] health analyzer text has readibility issues with so many organs and limbs. - **partially addressed in #6269**
- [x] surgery initiation should require a character to be laying down to work - **added in #6252**
- [x] surgeries for healing damage - **partially added in #6301**
- [x] more healing chems (currently implemented are antitoxin, anti-burn, and anti-damage.) - **partially added in #6308**
- [x] brain damage should result in death - **added in #6318**
- [x] Resting needs to be implemented - **partially added in #6252**
- [x] defibrillators - **added in #6231 and #6305**
- [x] CMO's mini defibrillator - **added in #6305**
- [x] healablejobedible.cs and donuts healing security personnel needs to be reimplemented. - **Fixed with #6318**
- [x] the chaplain's holy book healing needs to be reimplemented - **Fixed with #6318**

**Comment by waffielz** [comment]
moth wings don't clip to the main body

**Comment by corp-0** [comment]
People do take damage but it is not communicted to the UI.

**Comment by Aranclanos** [comment]
> People do take damage but it is not communicted to the UI.

not entirely sure because I spawned a bunch of lmgs and started shooting eachother with other people and nobody seemed to die after a million shots

**Comment by corp-0** [comment]
> not entirely sure because I spawned a bunch of lmgs and started shooting eachother with other people and nobody seemed to die after a million shots

I have the feeling stuff like weapons are looking for the old health class, same with mobs like the facehuggers.

**Comment by corp-0** [comment]
yeah, looks like all mobs are broken and can't hit you.

**Comment by corp-0** [comment]
Character button does nothing
![image](https://user-images.githubusercontent.com/43683714/110271756-6672d600-7fa7-11eb-86cf-f0567739c82f.png)

**Comment by AutumnNova** [comment]
did local testing, players seem to slowly die after taking any amount of brute damage?
![2021-03-08-14:53:58](https://user-images.githubusercontent.com/55225562/110272642-c22c7600-801e-11eb-94c4-c52bdaba9c0b.png)

**Comment by AutumnNova** [comment]
> People do take damage but it is not communicted to the UI.

seems to work serverside for whatever reason?

**Comment by waffielz** [comment]
clicking "revive" kicks admins from the server

**Comment by SluggyWuggies** [comment]
felinids randomly have basehuman model flicker when they move
cut wires cannot be picked up.. or pulled.

**Comment by AutumnNova** [comment]
> did local testing, players seem to slowly die after taking any amount of brute damage?


 seems if you spawn in you just slowly die regardless?

**Comment by AutumnNova** [comment]
> clicking "revive" kicks admins from the server

seems to work fine for me

**Comment by AutumnNova** [comment]
cat people seem to spawn with too many organs/limbs

**Comment by Cboyjet4** [comment]
You can also crit by cutting yourself in the arm

**Comment by AutumnNova** [comment]
![2021-03-09-12:56:59](https://user-images.githubusercontent.com/55225562/110406828-f5324080-80d6-11eb-99e2-a27b0442d9ee.png)
players hands are still not visable from the sides

**Comment by PetMudstone** [comment]
Using internal tanks (including oxygen ones) makes you seemingly die of oxygen loss. One can test this by turning on internals and watching your health doll slowly start turning red. Notably, disabling internals (while in a breathable atmosphere) causes your character to start recovering. According to the health analyzer, your character's body actually loses oxygen while gaining carbon dioxide and nitrogen. The used internals tank according to atmospherics analyzers also gains nitrogen and carbon dioxide after being used.
On a side note, dying from oxygen loss either from internal use or trying to breathe in an unbreathable environment does not create an O2 alert. Additionally, plasma is no longer dangerous to breathe in by itself.

**Comment by PetMudstone** [comment]
Also, health analyzer doesn't actually track oxyloss damage.

**Comment by PetMudstone** [comment]
Hands still render under jumpsuits but render over overwear such as hardsuits.

**Comment by MrAsbestos** [comment]
shoes too render under jumpsuits

**Comment by MrAsbestos** [comment]
Characters bleed (or give the impression to be hurt) when getting hit by any item or anything.

This is me hitting a dummy with a breath mask, an item which does absolutely no damage. 
https://user-images.githubusercontent.com/65787528/110724456-0a8c9500-81d3-11eb-9ceb-b2666c698630.mp4

**Comment by corp-0** [comment]
> plasma is no longer dangerous to breathe in by itself and needs to be reimplemented

air reagent toxicity and gas mask filtering air functionality, so it is more generic than just plasma.

**Comment by Cboyjet4** [comment]
would surgery be replaced with surgery illness?
We have a dynamic surgery system, so surgeries are not needed on this list.

**Comment by MrAsbestos** [comment]
Backpacks and gloves seem to render over items, items should and must be at the top.

![E5BkCq3q8X](https://user-images.githubusercontent.com/65787528/111183278-f945de80-856c-11eb-8802-9c429558d653.png)
You can see the backpack straps going through the sniper rifle.

![RyZ6wiDUkf](https://user-images.githubusercontent.com/65787528/111183914-a6205b80-856d-11eb-84b6-a75116120c6a.png)
Holding sunglasses with gloves

![ShareX_S20cKMafOY](https://user-images.githubusercontent.com/65787528/111183950-ad476980-856d-11eb-98c6-1feec942476c.png)
Holding sunglasses without gloves, you can see the details that were covered by the gloves.

And that's only the layering issues I have found

**Comment by corp-0** [comment]
> People dont seem to take damage?

this is not true.

**Comment by corp-0** [comment]
character creation: Random button does nothing.

**Comment by Aranclanos** [comment]
> > People dont seem to take damage?
> 
> this is not true.

At the time of writing we were shooting eachother with lmg's, which did nothing. That seem to have changed but I dont know if there's another type of dmg intake that doesnt use the new system

**Comment by corp-0** [comment]
sprites lagging behind clothes when turning seems to be local

**Comment by corp-0** [comment]
> At the time of writing we were shooting eachother with lmg's, which did nothing. That seem to have changed but I dont know if there's another type of dmg intake that doesnt use the new system

ah yes, that's because guns wanted to damage using LivingHealthBehaviour class. It was fixed, there might still be stuff trying to get that class though.

**Comment by corp-0** [comment]
> Right click rotate only rotates body parts

Not only right click rotate, it seems like the method we have to change facing other than movement (control + direction, for example) has the same problem.

**Comment by MaxIsJoe** [comment]
>  players spawning with a different character sheet

What does this mean?
I did notice that any characters saved before the health merge lost all their customization settings (I.e: skin color, hair, etc) but I have not encountered any issues after testing where players will spawn with wrong details on the server or client.

**Comment by PerfectTangent** [comment]
I believe that's related to #6202. Not sure if it's been fixed, though.

**Comment by Bod9001** [comment]
that was to do with the character settings not being able to changed while logged on server

**Comment by Aranclanos** [comment]
![image](https://user-images.githubusercontent.com/701959/112062303-832e1280-8b3e-11eb-9233-78acadef755a.png)
spikes of GC for bodypart updates

**Comment by Aranclanos** [comment]
![image](https://user-images.githubusercontent.com/701959/112546084-c1723e80-8d97-11eb-91bd-e88bb57ff1ee.png)
different parts of the project that calls for the old LivingHealthBehaviour to apply damage, notice that a variant of ApplyDamageToBodyPart() and ApplyDamage() also get called on different places

**Comment by Bod9001** [comment]
" once you have started resting in a bed, you cannot unrest anymore." 
is it being dragged onto a bed, because pressing the rest button on top of the bed shouldn't do anything apart from that youthe lie down like you do out of bed?

**Comment by PerfectTangent** [comment]
If you have buckled in to a bed, you cannot have surgery performed on you, so you must also rest. Once you do so, you cannot stop resting.

**Comment by corp-0** [comment]
when you drag your sprite to the bed are you supposed to buckle on it or rest?

**Comment by PerfectTangent** [comment]
mechanically, both. buckling in a bed should automatically be resting.

**Comment by PerfectTangent** [comment]
when you hit the rest button while in a bed, you already count as resting, so you would instead fall asleep.

**Comment by MaxIsJoe** [comment]
>  character sprites in the character customization window may not be rendering pixel perfect (needs investigation)

I think this has been fixed in #6313 as I do recall seeing a "Pixel Perfect" property inside the canvas ui being turned off but I've re-enabled it.

**Comment by PerfectTangent** [comment]
nice, alright. I'll check it off for now.

**Comment by PetMudstone** [comment]
You are unable to click on mobs in order to either attack them in melee or pet them. Mobs such as corgis are also currently unaffected by the vacuum of space.

**Comment by Aranclanos** [comment]
happy month anniversary!

**Comment by MaxIsJoe** [comment]
>  hair names dropdown list having long names,

Fixed in #6356 

> lizard tail is not correctly coloring to match the body

Fixed in #6357

**Comment by PetMudstone** [comment]
>  While crawling, you cannot pass through tiles that contain objects, including ones you should be able to such as light fixtures
Should be fixed in #6327

**Comment by MaxIsJoe** [comment]
> Action text rotates with the character when they are crawling. Sometimes it stays rotated after standing up.

Fixed in #6387 

>  if you try to crawl and emote at the same time, you're gonna have a bad time.

Because of how vague this issue is, I assume this has something to do with the issues I fixed where the player can go upside down or have the ability to do stuff while in critical condition or laying down. These issues have been fixed in #6387 , if this issue is indeed that then tick it off since it has been fixed and next time please be more clear about the issue even when you're joking about it or at least link a bug report so we know what we're hunting.

**Comment by MaxIsJoe** [comment]
> moth wings and antenna are not rendering in the correct spot from certain sprite facings, both in the character customization window and in game. Sometimes they are completely absent.

I think this issue has been fixed as I cannot replicate it.

**Comment by corp-0** [comment]
it should be fixed by now after Mudstone's Moth PRs

**Comment by PerfectTangent** [comment]
not completely fixed. The neck fluff is still not rendering how it should be, and a couple of the wing styles are rendering over the chest when they shouldn't be. It can't be checked off yet.

**Comment by MaxIsJoe** [comment]
>  if someone puts you inside a locker while you are crawling your client shows that you are standing but to everyone else you are crawling. When you stand up you stay rotated but are able to run at normal speed.

Fixed in #6410

**Comment by corp-0** [comment]
> not completely fixed. The neck fluff is still not rendering how it should be, and a couple of the wing styles are rendering over the chest when they shouldn't be. It can't be checked off yet.

The text says "antennae" and "wings", nothing about fluff. That's another new problem that was born after we decided to separate fluff from the rest of the sprite.

**Comment by PerfectTangent** [comment]
> > not completely fixed. The neck fluff is still not rendering how it should be, and a couple of the wing styles are rendering over the chest when they shouldn't be. It can't be checked off yet.
> 
> The text says "antennae" and "wings", nothing about fluff. That's another new problem that was born after we decided to separate fluff from the rest of the sprite.

it's still a problem with the customizeable parts of the moth, which like you point out, wasn't separate from wings originally until after that line was written. It's still a problem that needs to be solved.

**Comment by MaxIsJoe** [comment]
> the character preview in the character selector is not rendering pixel perfect.
 character sprites in the character customization window may not be rendering pixel perfect 

both these issues are fully fixed in #6440

**Comment by MaxIsJoe** [comment]
> the bright red vision constricting crit overlay persists after death sometimes.

I'm unable to replicate this, any idea what triggers it?

**Comment by PerfectTangent** [comment]
honestly, no. It was really common in the beginning, but I haven't seen it happen in ages. It may have been fixed at some point by other bug fixes.

**Comment by MaxIsJoe** [comment]
> removal of brain or head should result in death (lol)

This has been added.

**Comment by PerfectTangent** [comment]
cite the PR

**Comment by MaxIsJoe** [comment]
Its.. the one above mine.
#6610

**Comment by Fogapod** [comment]
> the bright red vision constricting crit overlay persists after death sometimes

I've been getting quite the opposite lately. I don't have crit circle at all sometimes. Don't know how to reproduce it, haven't seen related errors in f5 either, so not posted an issue yet

**Comment by corp-0** [comment]
I'm closing this issue not because we fixed everything but because this big list resulted to be untrackable and we will be making individual issues instead.
