### ISSUE TITLE
UnrealStation TODO list

### ISSUE THREAD

**Issue by PerfectTangent** [unitystation/unitystation#6435]
## TODO -

- [ ] fix #6421 
- [ ] fix #6581
- [ ] add atmos to the AI's room.
- [x] add a mineral silo to the station vault.
- [ ] standardize the hallway sizes.
- [ ] fill out several of the empty rooms.
- [ ] figure out a better way for science to fit together. Needing to go through robotics to get to toxins is no bueno.
- [ ] move sec hardsuits to a more appropriate place
- [ ] expand EVA storage. It needs oxygen tanks, magboots, and construction materials like other maps. maybe move it somewhere else?
- [ ] add a backup maint tunnel to get from arrivals to the rest of the station.
- [ ] expand the hab rooms. Maybe integrate with arrivals/evac?
- [ ] maybe just rework all of arrivals/evac. It's a mess.
- [ ] do some triage for medical's layout.
- [ ] consider moving the rage cage somewhere else. Maybe secret maintenance rage cage? idk.
- [ ] do a lighting pass.
- [ ] fill out perma with more furnishings and beds.
- [ ] rework and add beds to the sec cells.

**Comment by NoooneyDude** [comment]
- [ ] Has no wash rooms.
- [ ] Cargo lacking pens, paper bins and export scanners.
- [ ] Lacks an AutomatedAnnouncer.
- [ ] No circuit imprinter.

**Comment by corp-0** [comment]
Closing as the issue is quite old and has no progress. There is also a new mapping issue template that is better to track, since it is a single problem per issue.

Also UnrealStation is currently abandoned.
