### ISSUE TITLE
Mapping TODO List

### ISSUE THREAD

**Issue by ThatDan123** [unitystation/unitystation#6554]
- [x] Add Ore silos to each mainstation (in vault)
- [x] Add mining Equipment vendors to each mainstation
- [x] Add ore boxes to each mining room
- [x] Add Crayons and Spray cans to each mainstation
- [x] Change out surgery_12s in all scenes
- [x] Add at least 1 emergency storage room to each station, preferably near arrivals, Evac or the dorms. (done for box, outpost, ministation, fallstation, and squarestation)
- [x] Add a stationary syndicate base to all map specific versions of the nuke ops scene. It must include an operations console and at least 1 TC withdraw machine so War Ops is possible. All nuclear operative spawns should be moved to the syndicate base.
- [ ] Make sure all cell doors in security are linked to cell timers correctly
- [x] Add the automated announcer to Pog (added in #7186)
- [ ] Put status displays on escape shuttle for all maps
- [ ] Replace all the old heaters/freezers and put in the new ones after #6951
- [x] replace all instances of objects_110 with sec barriers

### Add ACUs to all maps and link devices

- [x] Boxstation (old air alarm prefabs should be replaced with new ACU ones)
- [x] Outpoststation (old air alarm prefabs should be replaced with new ACU ones)
- [x] fallstation
- [x] Squarestation
- [ ] centcom
- [ ] fall centcom
- [ ] lavaland
- [ ] syndicate
- [ ] fall syndicate

**Comment by Aranclanos** [comment]
I think some maps still dont have windoors linked to the wallmount monitor to enable it as a timer

**Comment by NoooneyDude** [comment]
Related issues: ~~#6882, #6871~~, #6619, #6581, #6435, #6421, #4145.

**Comment by NoooneyDude** [comment]
These pumps on Squarestation are installed backwards.

![backward pumps](https://i.imgur.com/LIbcx0d.png)

**Comment by ThatDan123** [comment]
Gonna add to the list "Put status displays on escape shuttle for all maps"

**Comment by corp-0** [comment]
Closing as the issue is quite old and has no progress. There is also a new mapping issue template that is better to track, since it is a single problem per issue.

If anything of this list is still a problem, it should be reported using said template.
