### ISSUE TITLE
De-syncronization Current List

### ISSUE THREAD

**Issue by pyrosshade** [unitystation/unitystation#6644]
Players have lately been reporting multiple forms of de-synchronization for a while now, but the number of reportings has recently increased since a recent pull request changing Networkidentities, pr #6531. It is unconfirmed as of yet whether or not it is the cause of these new issues, but there have been some mentions of desync even before this. Some issues are difficult to reproduce, and require thorough testing, to confirm if they still exist or to track down the source of the issue. Some issues may have a similiar root cause.

### IMPORTANT
Please keep in mind the following when testing:
1. The type of server being hosted (editor vs hub vs headless)
2. Reproduction steps (if any were provided)
3. One player connected vs. Multiple
4. Which players have late joined the round
5. Basic networking principles

### Known Issues
- [x] Objects are not properly despawning when smashed by an admin (and possibly under other situations) #6641
- [x] Teleporting To Different Matrix Bug #6591
- [x] Respawning Causes Random Teleporting #6637
- [ ] Character sprites buggy #6492
- [x] Asteroids (too close to the station?) can be flown through (encountered in editor)
- [ ] Crashing a shuttle while unbuckled may potentially send the player in the wrong direction, depending on the shuttle's roundstart direction and it's direction whilst crashing. May likely only ever throw in the direction of it's initial facing, however this is untested.
- [x] Grey crates are desynced in multiple ways, encountered on staging. Uninteractable in ancient engineering, and have potential to desync when: being pulled, when being pulled across matrices
- [ ] Bodies, living or dead can reach a state of being uninteractable, and even immune to being stuffed into a locker
- [x] Lavaland no longer teleports where it should.

**Comment by ThatDan123** [comment]
Since all those issues could be related, best to start looking at the crates in ancient station, could be the best way to have a reliable reproduction of the desyncs

**Comment by JukeJukestar** [comment]
Currently on staging (Build 21052720) and at seemingly random intervals all players are teleported into a single tile near arrivals. (Map: fallstation, but I have heard OOC reports that this happened on other maps aswell.) Could also be related to players changing matrix?

**Comment by pyrosshade** [comment]
> 
> 
> Currently on staging (Build 21052720) and at seemingly random intervals all players are teleported into a single tile near arrivals. (Map: fallstation, but I have heard OOC reports that this happened on other maps aswell.) Could also be related to players changing matrix?

related to #6637, as i stressed before it's not random intervals, but being triggered by other players changing matrix. I watched as a ghost as I saw someone manually trigger this by stepping onto and off of fallstation arrivals repeatedly and would reliably teleport other players to the arrivals.

**Comment by PerfectTangent** [comment]
Promoted to bounty. 150 USD to be split across everyone who opens PRs to fix these issues.

**Comment by pyrosshade** [comment]
Currently investigating ancient station itself, random teleporting bug seems reproducable there as well as the main station.

**Comment by Aranclanos** [comment]
![image](https://user-images.githubusercontent.com/701959/121559142-b620cd80-c9ec-11eb-899b-e17a23b7cce6.png)
doing tests with asteroids

**Comment by Aranclanos** [comment]
> Bodies, living or dead can reach a state of being uninteractable, and even immune to being stuffed into a locker

does this only happen on shuttle crashes or randomly?

**Comment by pyrosshade** [comment]
> 
> 
> > Bodies, living or dead can reach a state of being uninteractable, and even immune to being stuffed into a locker
> 
> does this only happen on shuttle crashes or randomly?

at the time this happened, the affected player was on station, hadn't gone anywhere, this will need testing to see if it can be reproduced

**Comment by PerfectTangent** [comment]
Removing the bounty on this issue as it has been very difficult measuring progress with it. The majority of the listed tasks have been closed due to not being reproduced and it's unclear which PRs fixed them, if any. also closing this issue since the remaining tasks have not been reported in a while either, and looking at them, I have _no idea_ how to even start to try to reproduce them.
