### ISSUE TITLE
syndicate base is broken pls fix <3

### ISSUE THREAD

**Issue by Leander-0** [unitystation/unitystation#7532]
### Environment
- Game Version: Staging 21100617
- OS Version: Arch Linux

### Detailed description of bug

MANY issues are present on the syndicate base where the nuclear operatives spawn.

(Edit) Summary:

- [ ] Syndicate base starts unpowered and there is no way to power it back (Electrical)
- [x] There are no buttons to get out of the base (Fixed on #7537)
- [x] Syndicate guns dont shoot under strange circumstances (Weapons) (Fixed on #7573)
- [x] War console once war is declared the countdown doesnt start (Fixed on #7573)
- [x] Syndicate shuttle is duplicated underneath, possibly the entire base is duplicated (Fixed on #7539)

## Power issues

first off when the nukies spawn on their rooms they are unable to exit out of them by normal means due to the base being unpowered and the doors being closed shut.

in this video you can see how connecting the plasma gen doesnt work to power the station, also all wires on the server get broken the moment the syndicate base is spawned:

might be related to issue #7333 

https://user-images.githubusercontent.com/80334192/136317326-a9463385-992e-4a0f-bc09-13fdaa71c881.mp4

## Buttons

the base lacks buttons to exit it and to access the syndicate shuttle

![button3](https://user-images.githubusercontent.com/80334192/136317562-3572349b-958c-4be7-8942-f8a6567a44c3.png)
![button2](https://user-images.githubusercontent.com/80334192/136317569-06c60522-4208-4217-9266-163a19f1c37e.png)
![button](https://user-images.githubusercontent.com/80334192/136317570-9d42d3e1-5780-422b-af12-ab2e937f5333.png)

## Syndicate Weapons

while testing it i tried shooting the syndicate guns on staging as a nukie and nothing happened. This error showed off in the console each time i tried to shoot a syndicate gun.

[error.txt](https://github.com/unitystation/unitystation/files/7298606/error.txt)

NOTE: i restarted the round and the first thing i did was respawning myself as a nukie, i immediately tried the guns and they shot without problems, however after i declared war in the war console they broke again somehow with the same error.

## War console countdown

when you declare war the countdown on the console doesnt start, however the TCs get deposited in the TC withdrawal consoles.

https://user-images.githubusercontent.com/80334192/136318295-f806eaf5-a318-45ea-82a9-481f54c88503.mp4

## Syndicate shuttle

i dont know what the heck is happening here, just respawn as a nukie on staging and try the same things done here.

might be related to #7493 

https://user-images.githubusercontent.com/80334192/136318479-4bb60d64-731e-4ff0-8a19-f0a3e3562cd0.mp4

NOTE2: this was all tested on the staging server squarestation map.

### Steps to reproduce

god pls send help too many bugs

**Comment by PerfectTangent** [comment]
@Leander-0 thanks for this, very thorough. Please try to separate bugs out into individual issues. Single issues describing a large array of bugs are difficult to track progress through, especially when there's also tons of visual evidence that obfuscates where things clearly end and begin. If you must combine multiple bug reports, at least itemize them with a checklist at the top of the issue so progression can be tracked.

**Comment by PerfectTangent** [comment]
can't reproduce the lack of power on the syndicate scene in the editor. It may be related to client desync or something, idk.

**Comment by corp-0** [comment]
what do the checkboxes represent here?

**Comment by Leander-0** [comment]
The checkboxes are to keep track of whats been fixed (maybe i should place the PRs that fixed those issues so its more organized).

**Comment by PetMudstone** [comment]
Note: The power bug this issue describes is only relevant when the round's map is Outpost or Square. Pog has no actual syndicate base and the Fall one is powered by magic (read: the self-powered variable) instead of a generator of any kind.

**Comment by Leander-0** [comment]
closing because mostly all was fixed, thank you all for fixing them <3!! 

also making an individual issue for the first one
