### ISSUE TITLE
The Big Bugs list

### ISSUE THREAD

**Issue by Bod9001** [unitystation/unitystation#7562]
- [x]  tile changes erroring
- [x] re-logging getting you a new character
- [ ] network objects not synchronising on relog
- [x] joining UI doesn't close itself
- [ ] power sometimes breaks
- [x] hunger ( lasts for ages but when you are hungry nothing seems to satiate it ) #7567 
- [x] Unable to deconstruct objects using screwdriver, cable panel is opened instead #7462
- [x] health states not synchronised properly
- [x] tile changes not synchronised
- [x] health balancing ( no indication to the user why they are dying, the feeling of sometimes being invincible whilst dying to stuff like fire)
- [x] Bleeding is too fast #7583 
- [x] head damage doesn't do any damage #7498
- [x] too much body part get damage goes down to lungs causing people to suffocate #7576
- [x] Null connection ban issue
- [x] Clothing gets cleared when you relog (I suspect issue is that on awake it clears but it gets set before it awakes)
- [x] Stuck on job select screen
- [ ] Dynamic inventory slot not updating ( item in in slot but cannot see it in slot )
- [x] dynamic inventory duplicating or not showing on clients ( rework to calculate the inventory should be, and changes to dynamic inventory should just give it a poke to check )
- [x] syndicate outpost is spawn causes electrical to break  ( tested this On editor as antagonist didn't Trigger it)
- [ ] inventory transfer message sometimes breaks on dynamic UI
- [x] Bullets should be server side
- [ ]  a-ghost  On a moving shuttle then return to body causes ghost to get stuck outside of body
- [x] Fire locks when closed go underneath doors blocking interaction, this should be on top when closed
- [x] lag yeah ( "also the server FPS started at 40, after i spawned the nukie base it went down to 13 FPS average" )
- [x] needs more mess for Janet to clean up for example bleeding
- [x] exploding projectiles Glitch out a lot server side confirmed ( passing through walls and stuff )
- [x] guns don't damage windows
- [x]  which character is used for playing the game seems to be random sometimes, and randomly brings up deleted characters #7571 
- [x] VV hierarchy search is laggy on server, optimise

**Comment by MaxIsJoe** [comment]
Can we be provided explanations to how they occur and steps? Preferably in a linked issue

**Comment by MaxIsJoe** [comment]
> health balancing
> hunger

this is too vague

**Comment by jamessimo** [comment]
is " Bleeding is too fast" still a valid bug? its linked to a closed issue.

**Comment by VernaSaurus** [comment]
> is " Bleeding is too fast" still a valid bug? its linked to a closed issue.

It shouldn't be, I fixed it at least three times

**Comment by corp-0** [comment]
I ticked some boxes. The idea was making those proper issues and adding them to [the project](https://github.com/unitystation/unitystation/projects/46) but it resulted to be hard to manage and a little vague

**Comment by corp-0** [comment]
I will be closing this since it was mostly fixed. If an issue from this list arises again, it should have its own github issue.
