### ISSUE TITLE
big admin tools and functions list

### ISSUE THREAD

**Issue by PerfectTangent** [unitystation/unitystation#8036]
### Core functions

- [ ] player manager and player chat windows need to be unified (#6506)
- [x] player praying
- [x] #6504
- [ ] player warnings
- [ ] #6503
- [ ] mute individual player
- [ ] player ban, jobban, admin notes, warnings, and appeals list (ticket system, basically)
- [ ] fix broken admin alerts (#6993)
- [ ] add searchable, navigable logs for active round and previous round
- [ ] (#7015, #7019)
- [x] Admin ranks (#5577)
- [ ] admin tools window scaling
- [x] separate staff chat from alerts/logs (completed in #8262)

### Roles and antags management

- [x] #5816
- [ ] manage job slots
- [ ] manage ghost roles
- [ ] manage antagonists/antag status
- [ ] antag tokens, mayhaps?
- [ ] create new jobs/ghost roles/antagonists
- [x] #4803 (completed in #8209)

### Event management

- [ ] see, disable, and create spawn points
- [ ] fly and teleport existing shuttles
- [ ] configure emergency shuttle type
- [ ] mob polymorph
- [ ] lavaland weather/event manager
- [ ] force a player's identity to be randomized on spawn
- [ ] disable away site for next round
- [ ] local and global narrate
- [ ] chat under fake identity in any channel (aka headset message)
- [ ] customizeable station security level
- [ ] drop bomb/meteor of variable power
- [ ] create custom chat polls
- [ ] place objects directly inside lockers and other containers.
- [ ] spawn preset scenes
- [ ] #6787 
- [ ] access newscaster
- [ ] access persistent library
- [ ] #6575 
- [x] #6438
- [x] give item function (completed in #8533)
- [x] #5322 (completed in #8438)

### Aghost and Aplayer interactivity

- [ ] de-admin (for yourself or an admin of a lower rank)
- [ ] repair object (without going through the VV)
- [ ] change identity
- [ ] Tile and matrix creation tools (and #7221)
- [ ] admin spawn window categories #7505 
- [ ] admin heal needs functionality improvement #7636 
- [ ] create and launch supply pods
- [ ] hide aghost sprite (#5229)
- [ ] admin throw/character toss

part of #4445
- [ ] ghosts should ignore clothing layers when accessing player inventory
- [ ] aghost access or use any console/machine
- [ ] allow aghosts to pick up items outside of a player's inventory
- [ ] allow aghosts to place items inside lockers/crates without opening them.

**Comment by Pockets-byte** [comment]
before steam release, I'd like to see a couple things. 
more intrusive rules, possibly toggable, an instant temporary removal from the round such as jail or character freeze, or both on right click. the ability to delete and smite characters on right click, the ability to maniplate shuttles, full permanent logging, and possibly an intrusive content warning on first boot of the game. also a way to ingame display the rules to certain players  


intrusive rules refers to a large rule window encountered on entering a server, possibly with a requirement to close, ideally togglable by admins, jailing refers to a quarantine zone in centcomn and it's z-level where possibly malicous actors can be deposited for either punishment or deciding of punishment, freeze is just a complete stop on a character for much the same purpose, smite/delete is qol and speed focused to remove bad actors asap, intrusive content warnings to discourage underage players from accessing the game, and the ability to display a full set of rules for players who don't earn themselves a ban

**Comment by potatoalienof13** [comment]
The ability to unban people is _really_ needed, and I don't see it here in this list.

**Comment by PerfectTangent** [comment]
> The ability to unban people is _really_ needed, and I don't see it here in this list.

that would be handled under this:

> - player ban, jobban, and warnings list

**Comment by Pockets-byte** [comment]
unban can be done temporarily with VV, and a server administrator can
remove the ban completely

**Comment by Pockets-byte** [comment]
https://tgstation13.org/wiki/Starter_guide_to_admin_tools
here's a handy list and pictures of all ss13 tools
and here's a handy other list of tools
https://archive.org/stream/pdfy-ctmgtzCGP1mwqGTu/tgStation13%20Admin%20Guide%20V1.1_djvu.txt

**Comment by Pockets-byte** [comment]
tile editing is done
